/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mocki2cmaster.h"

static const char* CMockString_data = "data";
static const char* CMockString_i2c_disable = "i2c_disable";
static const char* CMockString_i2c_enable = "i2c_enable";
static const char* CMockString_i2c_getData = "i2c_getData";
static const char* CMockString_i2c_readAck_nonblocking = "i2c_readAck_nonblocking";
static const char* CMockString_i2c_readNak_nonblocking = "i2c_readNak_nonblocking";
static const char* CMockString_i2c_start_nonblocking = "i2c_start_nonblocking";
static const char* CMockString_i2c_status = "i2c_status";
static const char* CMockString_i2c_stop_nonblocking = "i2c_stop_nonblocking";
static const char* CMockString_i2c_write_nonblocking = "i2c_write_nonblocking";

typedef struct _CMOCK_i2c_disable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_i2c_disable_CALL_INSTANCE;

typedef struct _CMOCK_i2c_enable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_i2c_enable_CALL_INSTANCE;

typedef struct _CMOCK_i2c_status_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_i2c_status_CALL_INSTANCE;

typedef struct _CMOCK_i2c_start_nonblocking_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_i2c_start_nonblocking_CALL_INSTANCE;

typedef struct _CMOCK_i2c_write_nonblocking_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  unsigned char Expected_data;

} CMOCK_i2c_write_nonblocking_CALL_INSTANCE;

typedef struct _CMOCK_i2c_readAck_nonblocking_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_i2c_readAck_nonblocking_CALL_INSTANCE;

typedef struct _CMOCK_i2c_readNak_nonblocking_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_i2c_readNak_nonblocking_CALL_INSTANCE;

typedef struct _CMOCK_i2c_stop_nonblocking_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_i2c_stop_nonblocking_CALL_INSTANCE;

typedef struct _CMOCK_i2c_getData_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_i2c_getData_CALL_INSTANCE;

static struct Mocki2cmasterInstance
{
  CMOCK_MEM_INDEX_TYPE i2c_disable_CallInstance;
  CMOCK_MEM_INDEX_TYPE i2c_enable_CallInstance;
  CMOCK_MEM_INDEX_TYPE i2c_status_CallInstance;
  CMOCK_MEM_INDEX_TYPE i2c_start_nonblocking_CallInstance;
  CMOCK_MEM_INDEX_TYPE i2c_write_nonblocking_CallInstance;
  CMOCK_MEM_INDEX_TYPE i2c_readAck_nonblocking_CallInstance;
  CMOCK_MEM_INDEX_TYPE i2c_readNak_nonblocking_CallInstance;
  CMOCK_MEM_INDEX_TYPE i2c_stop_nonblocking_CallInstance;
  CMOCK_MEM_INDEX_TYPE i2c_getData_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mocki2cmaster_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_i2c_disable);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.i2c_disable_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_i2c_enable);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.i2c_enable_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_i2c_status);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.i2c_status_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_i2c_start_nonblocking);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.i2c_start_nonblocking_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_i2c_write_nonblocking);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.i2c_write_nonblocking_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_i2c_readAck_nonblocking);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.i2c_readAck_nonblocking_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_i2c_readNak_nonblocking);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.i2c_readNak_nonblocking_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_i2c_stop_nonblocking);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.i2c_stop_nonblocking_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_i2c_getData);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.i2c_getData_CallInstance, cmock_line, CMockStringCalledLess);
}

void Mocki2cmaster_Init(void)
{
  Mocki2cmaster_Destroy();
}

void Mocki2cmaster_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void i2c_disable(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_i2c_disable_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_i2c_disable);
  cmock_call_instance = (CMOCK_i2c_disable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.i2c_disable_CallInstance);
  Mock.i2c_disable_CallInstance = CMock_Guts_MemNext(Mock.i2c_disable_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void i2c_disable_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_disable_CALL_INSTANCE));
  CMOCK_i2c_disable_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_disable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_disable_CallInstance = CMock_Guts_MemChain(Mock.i2c_disable_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void i2c_enable(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_i2c_enable_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_i2c_enable);
  cmock_call_instance = (CMOCK_i2c_enable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.i2c_enable_CallInstance);
  Mock.i2c_enable_CallInstance = CMock_Guts_MemNext(Mock.i2c_enable_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void i2c_enable_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_enable_CALL_INSTANCE));
  CMOCK_i2c_enable_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_enable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_enable_CallInstance = CMock_Guts_MemChain(Mock.i2c_enable_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

uint8_t i2c_status(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_i2c_status_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_i2c_status);
  cmock_call_instance = (CMOCK_i2c_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.i2c_status_CallInstance);
  Mock.i2c_status_CallInstance = CMock_Guts_MemNext(Mock.i2c_status_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void i2c_status_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_status_CALL_INSTANCE));
  CMOCK_i2c_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_status_CallInstance = CMock_Guts_MemChain(Mock.i2c_status_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void i2c_start_nonblocking(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_i2c_start_nonblocking_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_i2c_start_nonblocking);
  cmock_call_instance = (CMOCK_i2c_start_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.i2c_start_nonblocking_CallInstance);
  Mock.i2c_start_nonblocking_CallInstance = CMock_Guts_MemNext(Mock.i2c_start_nonblocking_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void i2c_start_nonblocking_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_start_nonblocking_CALL_INSTANCE));
  CMOCK_i2c_start_nonblocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_start_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_start_nonblocking_CallInstance = CMock_Guts_MemChain(Mock.i2c_start_nonblocking_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void i2c_write_nonblocking(unsigned char data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_i2c_write_nonblocking_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_i2c_write_nonblocking);
  cmock_call_instance = (CMOCK_i2c_write_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.i2c_write_nonblocking_CallInstance);
  Mock.i2c_write_nonblocking_CallInstance = CMock_Guts_MemNext(Mock.i2c_write_nonblocking_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_i2c_write_nonblocking,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_data, data, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_i2c_write_nonblocking(CMOCK_i2c_write_nonblocking_CALL_INSTANCE* cmock_call_instance, unsigned char data)
{
  cmock_call_instance->Expected_data = data;
}

void i2c_write_nonblocking_CMockExpect(UNITY_LINE_TYPE cmock_line, unsigned char data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_write_nonblocking_CALL_INSTANCE));
  CMOCK_i2c_write_nonblocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_write_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_write_nonblocking_CallInstance = CMock_Guts_MemChain(Mock.i2c_write_nonblocking_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_i2c_write_nonblocking(cmock_call_instance, data);
  UNITY_CLR_DETAILS();
}

void i2c_readAck_nonblocking(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_i2c_readAck_nonblocking_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_i2c_readAck_nonblocking);
  cmock_call_instance = (CMOCK_i2c_readAck_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.i2c_readAck_nonblocking_CallInstance);
  Mock.i2c_readAck_nonblocking_CallInstance = CMock_Guts_MemNext(Mock.i2c_readAck_nonblocking_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void i2c_readAck_nonblocking_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_readAck_nonblocking_CALL_INSTANCE));
  CMOCK_i2c_readAck_nonblocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_readAck_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_readAck_nonblocking_CallInstance = CMock_Guts_MemChain(Mock.i2c_readAck_nonblocking_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void i2c_readNak_nonblocking(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_i2c_readNak_nonblocking_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_i2c_readNak_nonblocking);
  cmock_call_instance = (CMOCK_i2c_readNak_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.i2c_readNak_nonblocking_CallInstance);
  Mock.i2c_readNak_nonblocking_CallInstance = CMock_Guts_MemNext(Mock.i2c_readNak_nonblocking_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void i2c_readNak_nonblocking_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_readNak_nonblocking_CALL_INSTANCE));
  CMOCK_i2c_readNak_nonblocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_readNak_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_readNak_nonblocking_CallInstance = CMock_Guts_MemChain(Mock.i2c_readNak_nonblocking_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void i2c_stop_nonblocking(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_i2c_stop_nonblocking_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_i2c_stop_nonblocking);
  cmock_call_instance = (CMOCK_i2c_stop_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.i2c_stop_nonblocking_CallInstance);
  Mock.i2c_stop_nonblocking_CallInstance = CMock_Guts_MemNext(Mock.i2c_stop_nonblocking_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void i2c_stop_nonblocking_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_stop_nonblocking_CALL_INSTANCE));
  CMOCK_i2c_stop_nonblocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_stop_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_stop_nonblocking_CallInstance = CMock_Guts_MemChain(Mock.i2c_stop_nonblocking_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

uint8_t i2c_getData(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_i2c_getData_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_i2c_getData);
  cmock_call_instance = (CMOCK_i2c_getData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.i2c_getData_CallInstance);
  Mock.i2c_getData_CallInstance = CMock_Guts_MemNext(Mock.i2c_getData_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void i2c_getData_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_getData_CALL_INSTANCE));
  CMOCK_i2c_getData_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_getData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_getData_CallInstance = CMock_Guts_MemChain(Mock.i2c_getData_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

