/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKDESCRIPTORS_H
#define _MOCKDESCRIPTORS_H

#include "unity.h"
#include "Descriptors.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void MockDescriptors_Init(void);
void MockDescriptors_Destroy(void);
void MockDescriptors_Verify(void);




#define CALLBACK_USB_GetDescriptor_ExpectAndReturn(wValue, wIndex, ATTR_NON_NULL_PTR_ARG(3, cmock_retval) CALLBACK_USB_GetDescriptor_CMockExpectAndReturn(__LINE__, wValue, wIndex, ATTR_NON_NULL_PTR_ARG(3, cmock_retval)
void CALLBACK_USB_GetDescriptor_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const uint16_t wValue, const uint8_t wIndex, const void** const DescriptorAddress)ATTR_WARN_UNUSED_RESULT ATTR_NON_NULL_PTR_ARG(3, uint16_t cmock_to_return);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
