/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mocksoftuart.h"

static const char* CMockString_ch = "ch";
static const char* CMockString_cmock_arg1 = "cmock_arg1";
static const char* CMockString_prg_s = "prg_s";
static const char* CMockString_s = "s";
static const char* CMockString_softuart_flush_input_buffer = "softuart_flush_input_buffer";
static const char* CMockString_softuart_getchar = "softuart_getchar";
static const char* CMockString_softuart_init = "softuart_init";
static const char* CMockString_softuart_kbhit = "softuart_kbhit";
static const char* CMockString_softuart_putchar = "softuart_putchar";
static const char* CMockString_softuart_putchar_blocking = "softuart_putchar_blocking";
static const char* CMockString_softuart_puts = "softuart_puts";
static const char* CMockString_softuart_puts_p = "softuart_puts_p";
static const char* CMockString_softuart_transmit_busy = "softuart_transmit_busy";
static const char* CMockString_softuart_turn_rx_off = "softuart_turn_rx_off";
static const char* CMockString_softuart_turn_rx_on = "softuart_turn_rx_on";

typedef struct _CMOCK_softuart_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_softuart_init_CALL_INSTANCE;

typedef struct _CMOCK_softuart_flush_input_buffer_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_softuart_flush_input_buffer_CALL_INSTANCE;

typedef struct _CMOCK_softuart_kbhit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  unsigned char ReturnVal;

} CMOCK_softuart_kbhit_CALL_INSTANCE;

typedef struct _CMOCK_softuart_getchar_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ReturnVal;

} CMOCK_softuart_getchar_CALL_INSTANCE;

typedef struct _CMOCK_softuart_transmit_busy_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  unsigned char ReturnVal;

} CMOCK_softuart_transmit_busy_CALL_INSTANCE;

typedef struct _CMOCK_softuart_putchar_blocking_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char Expected_ch;

} CMOCK_softuart_putchar_blocking_CALL_INSTANCE;

typedef struct _CMOCK_softuart_putchar_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char Expected_cmock_arg1;

} CMOCK_softuart_putchar_CALL_INSTANCE;

typedef struct _CMOCK_softuart_turn_rx_on_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_softuart_turn_rx_on_CALL_INSTANCE;

typedef struct _CMOCK_softuart_turn_rx_off_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_softuart_turn_rx_off_CALL_INSTANCE;

typedef struct _CMOCK_softuart_puts_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  const char* Expected_s;

} CMOCK_softuart_puts_CALL_INSTANCE;

typedef struct _CMOCK_softuart_puts_p_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  const char* Expected_prg_s;

} CMOCK_softuart_puts_p_CALL_INSTANCE;

static struct MocksoftuartInstance
{
  CMOCK_MEM_INDEX_TYPE softuart_init_CallInstance;
  CMOCK_MEM_INDEX_TYPE softuart_flush_input_buffer_CallInstance;
  CMOCK_MEM_INDEX_TYPE softuart_kbhit_CallInstance;
  CMOCK_MEM_INDEX_TYPE softuart_getchar_CallInstance;
  CMOCK_MEM_INDEX_TYPE softuart_transmit_busy_CallInstance;
  CMOCK_MEM_INDEX_TYPE softuart_putchar_blocking_CallInstance;
  CMOCK_MEM_INDEX_TYPE softuart_putchar_CallInstance;
  CMOCK_MEM_INDEX_TYPE softuart_turn_rx_on_CallInstance;
  CMOCK_MEM_INDEX_TYPE softuart_turn_rx_off_CallInstance;
  CMOCK_MEM_INDEX_TYPE softuart_puts_CallInstance;
  CMOCK_MEM_INDEX_TYPE softuart_puts_p_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mocksoftuart_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_softuart_init);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.softuart_init_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_softuart_flush_input_buffer);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.softuart_flush_input_buffer_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_softuart_kbhit);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.softuart_kbhit_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_softuart_getchar);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.softuart_getchar_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_softuart_transmit_busy);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.softuart_transmit_busy_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_softuart_putchar_blocking);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.softuart_putchar_blocking_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_softuart_putchar);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.softuart_putchar_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_softuart_turn_rx_on);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.softuart_turn_rx_on_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_softuart_turn_rx_off);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.softuart_turn_rx_off_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_softuart_puts);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.softuart_puts_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_softuart_puts_p);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.softuart_puts_p_CallInstance, cmock_line, CMockStringCalledLess);
}

void Mocksoftuart_Init(void)
{
  Mocksoftuart_Destroy();
}

void Mocksoftuart_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void softuart_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_softuart_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_softuart_init);
  cmock_call_instance = (CMOCK_softuart_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.softuart_init_CallInstance);
  Mock.softuart_init_CallInstance = CMock_Guts_MemNext(Mock.softuart_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void softuart_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_softuart_init_CALL_INSTANCE));
  CMOCK_softuart_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_softuart_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.softuart_init_CallInstance = CMock_Guts_MemChain(Mock.softuart_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void softuart_flush_input_buffer(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_softuart_flush_input_buffer_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_softuart_flush_input_buffer);
  cmock_call_instance = (CMOCK_softuart_flush_input_buffer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.softuart_flush_input_buffer_CallInstance);
  Mock.softuart_flush_input_buffer_CallInstance = CMock_Guts_MemNext(Mock.softuart_flush_input_buffer_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void softuart_flush_input_buffer_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_softuart_flush_input_buffer_CALL_INSTANCE));
  CMOCK_softuart_flush_input_buffer_CALL_INSTANCE* cmock_call_instance = (CMOCK_softuart_flush_input_buffer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.softuart_flush_input_buffer_CallInstance = CMock_Guts_MemChain(Mock.softuart_flush_input_buffer_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

unsigned char softuart_kbhit(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_softuart_kbhit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_softuart_kbhit);
  cmock_call_instance = (CMOCK_softuart_kbhit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.softuart_kbhit_CallInstance);
  Mock.softuart_kbhit_CallInstance = CMock_Guts_MemNext(Mock.softuart_kbhit_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void softuart_kbhit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, unsigned char cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_softuart_kbhit_CALL_INSTANCE));
  CMOCK_softuart_kbhit_CALL_INSTANCE* cmock_call_instance = (CMOCK_softuart_kbhit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.softuart_kbhit_CallInstance = CMock_Guts_MemChain(Mock.softuart_kbhit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

char softuart_getchar(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_softuart_getchar_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_softuart_getchar);
  cmock_call_instance = (CMOCK_softuart_getchar_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.softuart_getchar_CallInstance);
  Mock.softuart_getchar_CallInstance = CMock_Guts_MemNext(Mock.softuart_getchar_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void softuart_getchar_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_softuart_getchar_CALL_INSTANCE));
  CMOCK_softuart_getchar_CALL_INSTANCE* cmock_call_instance = (CMOCK_softuart_getchar_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.softuart_getchar_CallInstance = CMock_Guts_MemChain(Mock.softuart_getchar_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

unsigned char softuart_transmit_busy(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_softuart_transmit_busy_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_softuart_transmit_busy);
  cmock_call_instance = (CMOCK_softuart_transmit_busy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.softuart_transmit_busy_CallInstance);
  Mock.softuart_transmit_busy_CallInstance = CMock_Guts_MemNext(Mock.softuart_transmit_busy_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void softuart_transmit_busy_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, unsigned char cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_softuart_transmit_busy_CALL_INSTANCE));
  CMOCK_softuart_transmit_busy_CALL_INSTANCE* cmock_call_instance = (CMOCK_softuart_transmit_busy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.softuart_transmit_busy_CallInstance = CMock_Guts_MemChain(Mock.softuart_transmit_busy_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void softuart_putchar_blocking(const char ch)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_softuart_putchar_blocking_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_softuart_putchar_blocking);
  cmock_call_instance = (CMOCK_softuart_putchar_blocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.softuart_putchar_blocking_CallInstance);
  Mock.softuart_putchar_blocking_CallInstance = CMock_Guts_MemNext(Mock.softuart_putchar_blocking_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_softuart_putchar_blocking,CMockString_ch);
    UNITY_TEST_ASSERT_EQUAL_INT8(cmock_call_instance->Expected_ch, ch, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_softuart_putchar_blocking(CMOCK_softuart_putchar_blocking_CALL_INSTANCE* cmock_call_instance, const char ch)
{
  cmock_call_instance->Expected_ch = ch;
}

void softuart_putchar_blocking_CMockExpect(UNITY_LINE_TYPE cmock_line, const char ch)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_softuart_putchar_blocking_CALL_INSTANCE));
  CMOCK_softuart_putchar_blocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_softuart_putchar_blocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.softuart_putchar_blocking_CallInstance = CMock_Guts_MemChain(Mock.softuart_putchar_blocking_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_softuart_putchar_blocking(cmock_call_instance, ch);
  UNITY_CLR_DETAILS();
}

void softuart_putchar(const char cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_softuart_putchar_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_softuart_putchar);
  cmock_call_instance = (CMOCK_softuart_putchar_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.softuart_putchar_CallInstance);
  Mock.softuart_putchar_CallInstance = CMock_Guts_MemNext(Mock.softuart_putchar_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_softuart_putchar,CMockString_cmock_arg1);
    UNITY_TEST_ASSERT_EQUAL_INT8(cmock_call_instance->Expected_cmock_arg1, cmock_arg1, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_softuart_putchar(CMOCK_softuart_putchar_CALL_INSTANCE* cmock_call_instance, const char cmock_arg1)
{
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
}

void softuart_putchar_CMockExpect(UNITY_LINE_TYPE cmock_line, const char cmock_arg1)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_softuart_putchar_CALL_INSTANCE));
  CMOCK_softuart_putchar_CALL_INSTANCE* cmock_call_instance = (CMOCK_softuart_putchar_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.softuart_putchar_CallInstance = CMock_Guts_MemChain(Mock.softuart_putchar_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_softuart_putchar(cmock_call_instance, cmock_arg1);
  UNITY_CLR_DETAILS();
}

void softuart_turn_rx_on(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_softuart_turn_rx_on_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_softuart_turn_rx_on);
  cmock_call_instance = (CMOCK_softuart_turn_rx_on_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.softuart_turn_rx_on_CallInstance);
  Mock.softuart_turn_rx_on_CallInstance = CMock_Guts_MemNext(Mock.softuart_turn_rx_on_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void softuart_turn_rx_on_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_softuart_turn_rx_on_CALL_INSTANCE));
  CMOCK_softuart_turn_rx_on_CALL_INSTANCE* cmock_call_instance = (CMOCK_softuart_turn_rx_on_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.softuart_turn_rx_on_CallInstance = CMock_Guts_MemChain(Mock.softuart_turn_rx_on_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void softuart_turn_rx_off(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_softuart_turn_rx_off_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_softuart_turn_rx_off);
  cmock_call_instance = (CMOCK_softuart_turn_rx_off_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.softuart_turn_rx_off_CallInstance);
  Mock.softuart_turn_rx_off_CallInstance = CMock_Guts_MemNext(Mock.softuart_turn_rx_off_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void softuart_turn_rx_off_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_softuart_turn_rx_off_CALL_INSTANCE));
  CMOCK_softuart_turn_rx_off_CALL_INSTANCE* cmock_call_instance = (CMOCK_softuart_turn_rx_off_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.softuart_turn_rx_off_CallInstance = CMock_Guts_MemChain(Mock.softuart_turn_rx_off_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void softuart_puts(const char* s)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_softuart_puts_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_softuart_puts);
  cmock_call_instance = (CMOCK_softuart_puts_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.softuart_puts_CallInstance);
  Mock.softuart_puts_CallInstance = CMock_Guts_MemNext(Mock.softuart_puts_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_softuart_puts,CMockString_s);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_s, s, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_softuart_puts(CMOCK_softuart_puts_CALL_INSTANCE* cmock_call_instance, const char* s)
{
  cmock_call_instance->Expected_s = s;
}

void softuart_puts_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* s)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_softuart_puts_CALL_INSTANCE));
  CMOCK_softuart_puts_CALL_INSTANCE* cmock_call_instance = (CMOCK_softuart_puts_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.softuart_puts_CallInstance = CMock_Guts_MemChain(Mock.softuart_puts_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_softuart_puts(cmock_call_instance, s);
  UNITY_CLR_DETAILS();
}

void softuart_puts_p(const char* prg_s)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_softuart_puts_p_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_softuart_puts_p);
  cmock_call_instance = (CMOCK_softuart_puts_p_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.softuart_puts_p_CallInstance);
  Mock.softuart_puts_p_CallInstance = CMock_Guts_MemNext(Mock.softuart_puts_p_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_softuart_puts_p,CMockString_prg_s);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_prg_s, prg_s, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_softuart_puts_p(CMOCK_softuart_puts_p_CALL_INSTANCE* cmock_call_instance, const char* prg_s)
{
  cmock_call_instance->Expected_prg_s = prg_s;
}

void softuart_puts_p_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* prg_s)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_softuart_puts_p_CALL_INSTANCE));
  CMOCK_softuart_puts_p_CALL_INSTANCE* cmock_call_instance = (CMOCK_softuart_puts_p_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.softuart_puts_p_CallInstance = CMock_Guts_MemChain(Mock.softuart_puts_p_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_softuart_puts_p(cmock_call_instance, prg_s);
  UNITY_CLR_DETAILS();
}

