/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSOFTSERIAL_H
#define _MOCKSOFTSERIAL_H

#include "unity.h"
#include "softSerial.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void MocksoftSerial_Init(void);
void MocksoftSerial_Destroy(void);
void MocksoftSerial_Verify(void);




#define initSoftSerial_Expect() initSoftSerial_CMockExpect(__LINE__)
void initSoftSerial_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define readSoftString_ExpectAndReturn(cmock_retval) readSoftString_CMockExpectAndReturn(__LINE__, cmock_retval)
void readSoftString_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* cmock_to_return);
#define readSoftChar_ExpectAndReturn(cmock_retval) readSoftChar_CMockExpectAndReturn(__LINE__, cmock_retval)
void readSoftChar_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char cmock_to_return);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
