/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKUSBINTERFACE_H
#define _MOCKUSBINTERFACE_H

#include "unity.h"
#include "usbInterface.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void MockusbInterface_Init(void);
void MockusbInterface_Destroy(void);
void MockusbInterface_Verify(void);




#define usbSendChar_Expect(str) usbSendChar_CMockExpect(__LINE__, str)
void usbSendChar_CMockExpect(UNITY_LINE_TYPE cmock_line, char str);
#define usbSendString_Expect(str) usbSendString_CMockExpect(__LINE__, str)
void usbSendString_CMockExpect(UNITY_LINE_TYPE cmock_line, char* str);
#define usbTask_Expect() usbTask_CMockExpect(__LINE__)
void usbTask_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define usbReceiveChar_ExpectAndReturn(cmock_retval) usbReceiveChar_CMockExpectAndReturn(__LINE__, cmock_retval)
void usbReceiveChar_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char cmock_to_return);
#define EVENT_USB_Device_Connect_Expect() EVENT_USB_Device_Connect_CMockExpect(__LINE__)
void EVENT_USB_Device_Connect_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define EVENT_USB_Device_Disconnect_Expect() EVENT_USB_Device_Disconnect_CMockExpect(__LINE__)
void EVENT_USB_Device_Disconnect_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define EVENT_USB_Device_ConfigurationChanged_Expect() EVENT_USB_Device_ConfigurationChanged_CMockExpect(__LINE__)
void EVENT_USB_Device_ConfigurationChanged_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define EVENT_USB_Device_ControlRequest_Expect() EVENT_USB_Device_ControlRequest_CMockExpect(__LINE__)
void EVENT_USB_Device_ControlRequest_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define EVENT_CDC_Device_LineEncodingChanged_Expect(CDCInterfaceInfo) EVENT_CDC_Device_LineEncodingChanged_CMockExpect(__LINE__, CDCInterfaceInfo)
void EVENT_CDC_Device_LineEncodingChanged_CMockExpect(UNITY_LINE_TYPE cmock_line, USB_ClassInfo_CDC_Device_t* const CDCInterfaceInfo);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
