/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSOFTUART_H
#define _MOCKSOFTUART_H

#include "unity.h"
#include "softuart.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mocksoftuart_Init(void);
void Mocksoftuart_Destroy(void);
void Mocksoftuart_Verify(void);




#define softuart_init_Expect() softuart_init_CMockExpect(__LINE__)
void softuart_init_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define softuart_flush_input_buffer_Expect() softuart_flush_input_buffer_CMockExpect(__LINE__)
void softuart_flush_input_buffer_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define softuart_kbhit_ExpectAndReturn(cmock_retval) softuart_kbhit_CMockExpectAndReturn(__LINE__, cmock_retval)
void softuart_kbhit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, unsigned char cmock_to_return);
#define softuart_getchar_ExpectAndReturn(cmock_retval) softuart_getchar_CMockExpectAndReturn(__LINE__, cmock_retval)
void softuart_getchar_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char cmock_to_return);
#define softuart_transmit_busy_ExpectAndReturn(cmock_retval) softuart_transmit_busy_CMockExpectAndReturn(__LINE__, cmock_retval)
void softuart_transmit_busy_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, unsigned char cmock_to_return);
#define softuart_putchar_blocking_Expect(ch) softuart_putchar_blocking_CMockExpect(__LINE__, ch)
void softuart_putchar_blocking_CMockExpect(UNITY_LINE_TYPE cmock_line, const char ch);
#define softuart_putchar_Expect(cmock_arg1) softuart_putchar_CMockExpect(__LINE__, cmock_arg1)
void softuart_putchar_CMockExpect(UNITY_LINE_TYPE cmock_line, const char cmock_arg1);
#define softuart_turn_rx_on_Expect() softuart_turn_rx_on_CMockExpect(__LINE__)
void softuart_turn_rx_on_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define softuart_turn_rx_off_Expect() softuart_turn_rx_off_CMockExpect(__LINE__)
void softuart_turn_rx_off_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define softuart_puts_Expect(s) softuart_puts_CMockExpect(__LINE__, s)
void softuart_puts_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* s);
#define softuart_puts_p_Expect(prg_s) softuart_puts_p_CMockExpect(__LINE__, prg_s)
void softuart_puts_p_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* prg_s);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
