/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "MocksoftSerial.h"

static const char* CMockString_initSoftSerial = "initSoftSerial";
static const char* CMockString_readSoftChar = "readSoftChar";
static const char* CMockString_readSoftString = "readSoftString";

typedef struct _CMOCK_initSoftSerial_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_initSoftSerial_CALL_INSTANCE;

typedef struct _CMOCK_readSoftString_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char* ReturnVal;

} CMOCK_readSoftString_CALL_INSTANCE;

typedef struct _CMOCK_readSoftChar_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ReturnVal;

} CMOCK_readSoftChar_CALL_INSTANCE;

static struct MocksoftSerialInstance
{
  CMOCK_MEM_INDEX_TYPE initSoftSerial_CallInstance;
  CMOCK_MEM_INDEX_TYPE readSoftString_CallInstance;
  CMOCK_MEM_INDEX_TYPE readSoftChar_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MocksoftSerial_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_initSoftSerial);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.initSoftSerial_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_readSoftString);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.readSoftString_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_readSoftChar);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.readSoftChar_CallInstance, cmock_line, CMockStringCalledLess);
}

void MocksoftSerial_Init(void)
{
  MocksoftSerial_Destroy();
}

void MocksoftSerial_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void initSoftSerial(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_initSoftSerial_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_initSoftSerial);
  cmock_call_instance = (CMOCK_initSoftSerial_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.initSoftSerial_CallInstance);
  Mock.initSoftSerial_CallInstance = CMock_Guts_MemNext(Mock.initSoftSerial_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void initSoftSerial_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_initSoftSerial_CALL_INSTANCE));
  CMOCK_initSoftSerial_CALL_INSTANCE* cmock_call_instance = (CMOCK_initSoftSerial_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.initSoftSerial_CallInstance = CMock_Guts_MemChain(Mock.initSoftSerial_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

char* readSoftString(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_readSoftString_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_readSoftString);
  cmock_call_instance = (CMOCK_readSoftString_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.readSoftString_CallInstance);
  Mock.readSoftString_CallInstance = CMock_Guts_MemNext(Mock.readSoftString_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void readSoftString_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_readSoftString_CALL_INSTANCE));
  CMOCK_readSoftString_CALL_INSTANCE* cmock_call_instance = (CMOCK_readSoftString_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.readSoftString_CallInstance = CMock_Guts_MemChain(Mock.readSoftString_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

char readSoftChar(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_readSoftChar_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_readSoftChar);
  cmock_call_instance = (CMOCK_readSoftChar_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.readSoftChar_CallInstance);
  Mock.readSoftChar_CallInstance = CMock_Guts_MemNext(Mock.readSoftChar_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void readSoftChar_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, char cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_readSoftChar_CALL_INSTANCE));
  CMOCK_readSoftChar_CALL_INSTANCE* cmock_call_instance = (CMOCK_readSoftChar_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.readSoftChar_CallInstance = CMock_Guts_MemChain(Mock.readSoftChar_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

