/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "MockDescriptors.h"

static const char* CMockString_ATTR_NON_NULL_PTR_ARG(3 = "ATTR_NON_NULL_PTR_ARG(3";
static const char* CMockString_CALLBACK_USB_GetDescriptor = "CALLBACK_USB_GetDescriptor";
static const char* CMockString_wIndex = "wIndex";
static const char* CMockString_wValue = "wValue";

typedef struct _CMOCK_CALLBACK_USB_GetDescriptor_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;
  uint16_t Expected_wValue;
  uint8_t Expected_wIndex;
  const void** DescriptorAddress)ATTR_WARN_UNUSED_RESULT Expected_ATTR_NON_NULL_PTR_ARG(3;

} CMOCK_CALLBACK_USB_GetDescriptor_CALL_INSTANCE;

static struct MockDescriptorsInstance
{
  CMOCK_MEM_INDEX_TYPE CALLBACK_USB_GetDescriptor_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockDescriptors_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_CALLBACK_USB_GetDescriptor);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.CALLBACK_USB_GetDescriptor_CallInstance, cmock_line, CMockStringCalledLess);
}

void MockDescriptors_Init(void)
{
  MockDescriptors_Destroy();
}

void MockDescriptors_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

uint16_t CALLBACK_USB_GetDescriptor(const uint16_t wValue, const uint8_t wIndex, const void** const DescriptorAddress)ATTR_WARN_UNUSED_RESULT ATTR_NON_NULL_PTR_ARG(3)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_CALLBACK_USB_GetDescriptor_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_CALLBACK_USB_GetDescriptor);
  cmock_call_instance = (CMOCK_CALLBACK_USB_GetDescriptor_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.CALLBACK_USB_GetDescriptor_CallInstance);
  Mock.CALLBACK_USB_GetDescriptor_CallInstance = CMock_Guts_MemNext(Mock.CALLBACK_USB_GetDescriptor_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_CALLBACK_USB_GetDescriptor,CMockString_wValue);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_wValue, wValue, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_CALLBACK_USB_GetDescriptor,CMockString_wIndex);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_wIndex, wIndex, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_CALLBACK_USB_GetDescriptor,CMockString_ATTR_NON_NULL_PTR_ARG(3);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_ATTR_NON_NULL_PTR_ARG(3, ATTR_NON_NULL_PTR_ARG(3, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_CALLBACK_USB_GetDescriptor(CMOCK_CALLBACK_USB_GetDescriptor_CALL_INSTANCE* cmock_call_instance, const uint16_t wValue, const uint8_t wIndex, const void** const DescriptorAddress)ATTR_WARN_UNUSED_RESULT ATTR_NON_NULL_PTR_ARG(3)
{
  cmock_call_instance->Expected_wValue = wValue;
  cmock_call_instance->Expected_wIndex = wIndex;
  cmock_call_instance->Expected_ATTR_NON_NULL_PTR_ARG(3 = ATTR_NON_NULL_PTR_ARG(3;
}

void CALLBACK_USB_GetDescriptor_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const uint16_t wValue, const uint8_t wIndex, const void** const DescriptorAddress)ATTR_WARN_UNUSED_RESULT ATTR_NON_NULL_PTR_ARG(3, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_CALLBACK_USB_GetDescriptor_CALL_INSTANCE));
  CMOCK_CALLBACK_USB_GetDescriptor_CALL_INSTANCE* cmock_call_instance = (CMOCK_CALLBACK_USB_GetDescriptor_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.CALLBACK_USB_GetDescriptor_CallInstance = CMock_Guts_MemChain(Mock.CALLBACK_USB_GetDescriptor_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_CALLBACK_USB_GetDescriptor(cmock_call_instance, wValue, wIndex, ATTR_NON_NULL_PTR_ARG(3);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

