/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockdebug.h"

static const char* CMockString_c = "c";
static const char* CMockString_debugAck = "debugAck";
static const char* CMockString_debugDisable = "debugDisable";
static const char* CMockString_debugDone = "debugDone";
static const char* CMockString_debugEnable = "debugEnable";
static const char* CMockString_debugGetChar = "debugGetChar";
static const char* CMockString_debugInit = "debugInit";
static const char* CMockString_debugNewLine = "debugNewLine";
static const char* CMockString_debugReadChar = "debugReadChar";
static const char* CMockString_debugReadCharAvailable = "debugReadCharAvailable";
static const char* CMockString_debugReadCharProcessed = "debugReadCharProcessed";
static const char* CMockString_debugReady = "debugReady";
static const char* CMockString_debugSending = "debugSending";
static const char* CMockString_debugWaitUntilDone = "debugWaitUntilDone";
static const char* CMockString_debugWriteBin32 = "debugWriteBin32";
static const char* CMockString_debugWriteBin4 = "debugWriteBin4";
static const char* CMockString_debugWriteBin8 = "debugWriteBin8";
static const char* CMockString_debugWriteBool = "debugWriteBool";
static const char* CMockString_debugWriteChar = "debugWriteChar";
static const char* CMockString_debugWriteCharBlock = "debugWriteCharBlock";
static const char* CMockString_debugWriteCharHelper = "debugWriteCharHelper";
static const char* CMockString_debugWriteDec16 = "debugWriteDec16";
static const char* CMockString_debugWriteDec32 = "debugWriteDec32";
static const char* CMockString_debugWriteDec32S = "debugWriteDec32S";
static const char* CMockString_debugWriteDec8 = "debugWriteDec8";
static const char* CMockString_debugWriteFloat = "debugWriteFloat";
static const char* CMockString_debugWriteFloatFull = "debugWriteFloatFull";
static const char* CMockString_debugWriteHex16 = "debugWriteHex16";
static const char* CMockString_debugWriteHex32 = "debugWriteHex32";
static const char* CMockString_debugWriteHex8 = "debugWriteHex8";
static const char* CMockString_debugWriteHex8Helper = "debugWriteHex8Helper";
static const char* CMockString_debugWriteLine = "debugWriteLine";
static const char* CMockString_debugWriteString = "debugWriteString";
static const char* CMockString_debugWriteStringLength = "debugWriteStringLength";
static const char* CMockString_input = "input";
static const char* CMockString_last = "last";
static const char* CMockString_length = "length";
static const char* CMockString_num = "num";
static const char* CMockString_printUartHandler = "printUartHandler";
static const char* CMockString_receiveHandler = "receiveHandler";
static const char* CMockString_s = "s";
static const char* CMockString_setDebugReceiveHandler = "setDebugReceiveHandler";

typedef struct _CMOCK_debugEnable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_debugEnable_CALL_INSTANCE;

typedef struct _CMOCK_debugDisable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_debugDisable_CALL_INSTANCE;

typedef struct _CMOCK_debugInit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  cmock_debug_func_ptr1 Expected_receiveHandler;

} CMOCK_debugInit_CALL_INSTANCE;

typedef struct _CMOCK_setDebugReceiveHandler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  cmock_debug_func_ptr2 Expected_receiveHandler;

} CMOCK_setDebugReceiveHandler_CALL_INSTANCE;

typedef struct _CMOCK_debugNewLine_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_debugNewLine_CALL_INSTANCE;

typedef struct _CMOCK_debugWriteBool_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t Expected_input;

} CMOCK_debugWriteBool_CALL_INSTANCE;

typedef struct _CMOCK_debugWriteLine_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char* Expected_s;

} CMOCK_debugWriteLine_CALL_INSTANCE;

typedef struct _CMOCK_debugWriteString_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char* Expected_s;

} CMOCK_debugWriteString_CALL_INSTANCE;

typedef struct _CMOCK_debugWriteStringLength_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char* Expected_s;
  uint8_t Expected_length;

} CMOCK_debugWriteStringLength_CALL_INSTANCE;

typedef struct _CMOCK_debugWriteChar_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t Expected_c;

} CMOCK_debugWriteChar_CALL_INSTANCE;

typedef struct _CMOCK_debugWriteCharBlock_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t Expected_c;

} CMOCK_debugWriteCharBlock_CALL_INSTANCE;

typedef struct _CMOCK_debugWriteCharHelper_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t Expected_c;
  uint8_t Expected_last;

} CMOCK_debugWriteCharHelper_CALL_INSTANCE;

typedef struct _CMOCK_debugReadChar_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_debugReadChar_CALL_INSTANCE;

typedef struct _CMOCK_debugReadCharAvailable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_debugReadCharAvailable_CALL_INSTANCE;

typedef struct _CMOCK_debugReadCharProcessed_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_debugReadCharProcessed_CALL_INSTANCE;

typedef struct _CMOCK_debugGetChar_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_debugGetChar_CALL_INSTANCE;

typedef struct _CMOCK_debugWriteHex8_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t Expected_num;

} CMOCK_debugWriteHex8_CALL_INSTANCE;

typedef struct _CMOCK_debugWriteHex8Helper_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t Expected_num;
  uint8_t Expected_last;

} CMOCK_debugWriteHex8Helper_CALL_INSTANCE;

typedef struct _CMOCK_debugWriteHex16_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t Expected_num;

} CMOCK_debugWriteHex16_CALL_INSTANCE;

typedef struct _CMOCK_debugWriteDec8_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t Expected_num;

} CMOCK_debugWriteDec8_CALL_INSTANCE;

typedef struct _CMOCK_debugWriteDec16_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t Expected_num;

} CMOCK_debugWriteDec16_CALL_INSTANCE;

typedef struct _CMOCK_debugWriteBin8_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t Expected_num;

} CMOCK_debugWriteBin8_CALL_INSTANCE;

typedef struct _CMOCK_debugWriteHex32_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t Expected_num;

} CMOCK_debugWriteHex32_CALL_INSTANCE;

typedef struct _CMOCK_debugWriteBin32_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t Expected_num;

} CMOCK_debugWriteBin32_CALL_INSTANCE;

typedef struct _CMOCK_debugWriteFloat_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  float Expected_num;

} CMOCK_debugWriteFloat_CALL_INSTANCE;

typedef struct _CMOCK_debugWriteFloatFull_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  float Expected_num;

} CMOCK_debugWriteFloatFull_CALL_INSTANCE;

typedef struct _CMOCK_debugWriteBin4_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t Expected_num;

} CMOCK_debugWriteBin4_CALL_INSTANCE;

typedef struct _CMOCK_debugWriteDec32_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t Expected_num;

} CMOCK_debugWriteDec32_CALL_INSTANCE;

typedef struct _CMOCK_debugWriteDec32S_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  int32_t Expected_num;

} CMOCK_debugWriteDec32S_CALL_INSTANCE;

typedef struct _CMOCK_debugDone_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_debugDone_CALL_INSTANCE;

typedef struct _CMOCK_debugReady_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_debugReady_CALL_INSTANCE;

typedef struct _CMOCK_debugWaitUntilDone_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_debugWaitUntilDone_CALL_INSTANCE;

typedef struct _CMOCK_debugSending_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_debugSending_CALL_INSTANCE;

typedef struct _CMOCK_debugAck_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t Expected_c;

} CMOCK_debugAck_CALL_INSTANCE;

typedef struct _CMOCK_printUartHandler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_printUartHandler_CALL_INSTANCE;

static struct MockdebugInstance
{
  CMOCK_MEM_INDEX_TYPE debugEnable_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugDisable_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugInit_CallInstance;
  CMOCK_MEM_INDEX_TYPE setDebugReceiveHandler_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugNewLine_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugWriteBool_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugWriteLine_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugWriteString_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugWriteStringLength_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugWriteChar_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugWriteCharBlock_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugWriteCharHelper_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugReadChar_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugReadCharAvailable_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugReadCharProcessed_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugGetChar_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugWriteHex8_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugWriteHex8Helper_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugWriteHex16_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugWriteDec8_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugWriteDec16_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugWriteBin8_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugWriteHex32_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugWriteBin32_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugWriteFloat_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugWriteFloatFull_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugWriteBin4_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugWriteDec32_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugWriteDec32S_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugDone_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugReady_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugWaitUntilDone_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugSending_CallInstance;
  CMOCK_MEM_INDEX_TYPE debugAck_CallInstance;
  CMOCK_MEM_INDEX_TYPE printUartHandler_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockdebug_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_debugEnable);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugEnable_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugDisable);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugDisable_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugInit);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugInit_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_setDebugReceiveHandler);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.setDebugReceiveHandler_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugNewLine);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugNewLine_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugWriteBool);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugWriteBool_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugWriteLine);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugWriteLine_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugWriteString);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugWriteString_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugWriteStringLength);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugWriteStringLength_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugWriteChar);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugWriteChar_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugWriteCharBlock);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugWriteCharBlock_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugWriteCharHelper);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugWriteCharHelper_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugReadChar);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugReadChar_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugReadCharAvailable);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugReadCharAvailable_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugReadCharProcessed);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugReadCharProcessed_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugGetChar);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugGetChar_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugWriteHex8);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugWriteHex8_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugWriteHex8Helper);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugWriteHex8Helper_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugWriteHex16);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugWriteHex16_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugWriteDec8);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugWriteDec8_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugWriteDec16);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugWriteDec16_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugWriteBin8);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugWriteBin8_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugWriteHex32);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugWriteHex32_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugWriteBin32);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugWriteBin32_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugWriteFloat);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugWriteFloat_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugWriteFloatFull);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugWriteFloatFull_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugWriteBin4);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugWriteBin4_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugWriteDec32);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugWriteDec32_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugWriteDec32S);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugWriteDec32S_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugDone);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugDone_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugReady);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugReady_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugWaitUntilDone);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugWaitUntilDone_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugSending);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugSending_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_debugAck);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.debugAck_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_printUartHandler);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.printUartHandler_CallInstance, cmock_line, CMockStringCalledLess);
}

void Mockdebug_Init(void)
{
  Mockdebug_Destroy();
}

void Mockdebug_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void debugEnable(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugEnable_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugEnable);
  cmock_call_instance = (CMOCK_debugEnable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugEnable_CallInstance);
  Mock.debugEnable_CallInstance = CMock_Guts_MemNext(Mock.debugEnable_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void debugEnable_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugEnable_CALL_INSTANCE));
  CMOCK_debugEnable_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugEnable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugEnable_CallInstance = CMock_Guts_MemChain(Mock.debugEnable_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void debugDisable(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugDisable_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugDisable);
  cmock_call_instance = (CMOCK_debugDisable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugDisable_CallInstance);
  Mock.debugDisable_CallInstance = CMock_Guts_MemNext(Mock.debugDisable_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void debugDisable_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugDisable_CALL_INSTANCE));
  CMOCK_debugDisable_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugDisable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugDisable_CallInstance = CMock_Guts_MemChain(Mock.debugDisable_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void debugInit(cmock_debug_func_ptr1 receiveHandler)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugInit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugInit);
  cmock_call_instance = (CMOCK_debugInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugInit_CallInstance);
  Mock.debugInit_CallInstance = CMock_Guts_MemNext(Mock.debugInit_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_debugInit,CMockString_receiveHandler);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_receiveHandler, receiveHandler, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_debugInit(CMOCK_debugInit_CALL_INSTANCE* cmock_call_instance, cmock_debug_func_ptr1 receiveHandler)
{
  memcpy(&cmock_call_instance->Expected_receiveHandler, &receiveHandler, sizeof(cmock_debug_func_ptr1));
}

void debugInit_CMockExpect(UNITY_LINE_TYPE cmock_line, cmock_debug_func_ptr1 receiveHandler)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugInit_CALL_INSTANCE));
  CMOCK_debugInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugInit_CallInstance = CMock_Guts_MemChain(Mock.debugInit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debugInit(cmock_call_instance, receiveHandler);
  UNITY_CLR_DETAILS();
}

void setDebugReceiveHandler(cmock_debug_func_ptr2 receiveHandler)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_setDebugReceiveHandler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_setDebugReceiveHandler);
  cmock_call_instance = (CMOCK_setDebugReceiveHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.setDebugReceiveHandler_CallInstance);
  Mock.setDebugReceiveHandler_CallInstance = CMock_Guts_MemNext(Mock.setDebugReceiveHandler_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_setDebugReceiveHandler,CMockString_receiveHandler);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_receiveHandler, receiveHandler, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_setDebugReceiveHandler(CMOCK_setDebugReceiveHandler_CALL_INSTANCE* cmock_call_instance, cmock_debug_func_ptr2 receiveHandler)
{
  memcpy(&cmock_call_instance->Expected_receiveHandler, &receiveHandler, sizeof(cmock_debug_func_ptr2));
}

void setDebugReceiveHandler_CMockExpect(UNITY_LINE_TYPE cmock_line, cmock_debug_func_ptr2 receiveHandler)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_setDebugReceiveHandler_CALL_INSTANCE));
  CMOCK_setDebugReceiveHandler_CALL_INSTANCE* cmock_call_instance = (CMOCK_setDebugReceiveHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.setDebugReceiveHandler_CallInstance = CMock_Guts_MemChain(Mock.setDebugReceiveHandler_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_setDebugReceiveHandler(cmock_call_instance, receiveHandler);
  UNITY_CLR_DETAILS();
}

void debugNewLine(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugNewLine_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugNewLine);
  cmock_call_instance = (CMOCK_debugNewLine_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugNewLine_CallInstance);
  Mock.debugNewLine_CallInstance = CMock_Guts_MemNext(Mock.debugNewLine_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void debugNewLine_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugNewLine_CALL_INSTANCE));
  CMOCK_debugNewLine_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugNewLine_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugNewLine_CallInstance = CMock_Guts_MemChain(Mock.debugNewLine_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void debugWriteBool(uint8_t input)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugWriteBool_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugWriteBool);
  cmock_call_instance = (CMOCK_debugWriteBool_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugWriteBool_CallInstance);
  Mock.debugWriteBool_CallInstance = CMock_Guts_MemNext(Mock.debugWriteBool_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_debugWriteBool,CMockString_input);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_input, input, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_debugWriteBool(CMOCK_debugWriteBool_CALL_INSTANCE* cmock_call_instance, uint8_t input)
{
  cmock_call_instance->Expected_input = input;
}

void debugWriteBool_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t input)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugWriteBool_CALL_INSTANCE));
  CMOCK_debugWriteBool_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugWriteBool_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugWriteBool_CallInstance = CMock_Guts_MemChain(Mock.debugWriteBool_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debugWriteBool(cmock_call_instance, input);
  UNITY_CLR_DETAILS();
}

void debugWriteLine(char* s)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugWriteLine_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugWriteLine);
  cmock_call_instance = (CMOCK_debugWriteLine_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugWriteLine_CallInstance);
  Mock.debugWriteLine_CallInstance = CMock_Guts_MemNext(Mock.debugWriteLine_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_debugWriteLine,CMockString_s);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_s, s, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_debugWriteLine(CMOCK_debugWriteLine_CALL_INSTANCE* cmock_call_instance, char* s)
{
  cmock_call_instance->Expected_s = s;
}

void debugWriteLine_CMockExpect(UNITY_LINE_TYPE cmock_line, char* s)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugWriteLine_CALL_INSTANCE));
  CMOCK_debugWriteLine_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugWriteLine_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugWriteLine_CallInstance = CMock_Guts_MemChain(Mock.debugWriteLine_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debugWriteLine(cmock_call_instance, s);
  UNITY_CLR_DETAILS();
}

void debugWriteString(char* s)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugWriteString_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugWriteString);
  cmock_call_instance = (CMOCK_debugWriteString_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugWriteString_CallInstance);
  Mock.debugWriteString_CallInstance = CMock_Guts_MemNext(Mock.debugWriteString_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_debugWriteString,CMockString_s);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_s, s, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_debugWriteString(CMOCK_debugWriteString_CALL_INSTANCE* cmock_call_instance, char* s)
{
  cmock_call_instance->Expected_s = s;
}

void debugWriteString_CMockExpect(UNITY_LINE_TYPE cmock_line, char* s)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugWriteString_CALL_INSTANCE));
  CMOCK_debugWriteString_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugWriteString_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugWriteString_CallInstance = CMock_Guts_MemChain(Mock.debugWriteString_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debugWriteString(cmock_call_instance, s);
  UNITY_CLR_DETAILS();
}

void debugWriteStringLength(char* s, uint8_t length)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugWriteStringLength_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugWriteStringLength);
  cmock_call_instance = (CMOCK_debugWriteStringLength_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugWriteStringLength_CallInstance);
  Mock.debugWriteStringLength_CallInstance = CMock_Guts_MemNext(Mock.debugWriteStringLength_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_debugWriteStringLength,CMockString_s);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_s, s, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_debugWriteStringLength,CMockString_length);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_length, length, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_debugWriteStringLength(CMOCK_debugWriteStringLength_CALL_INSTANCE* cmock_call_instance, char* s, uint8_t length)
{
  cmock_call_instance->Expected_s = s;
  cmock_call_instance->Expected_length = length;
}

void debugWriteStringLength_CMockExpect(UNITY_LINE_TYPE cmock_line, char* s, uint8_t length)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugWriteStringLength_CALL_INSTANCE));
  CMOCK_debugWriteStringLength_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugWriteStringLength_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugWriteStringLength_CallInstance = CMock_Guts_MemChain(Mock.debugWriteStringLength_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debugWriteStringLength(cmock_call_instance, s, length);
  UNITY_CLR_DETAILS();
}

void debugWriteChar(uint8_t c)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugWriteChar_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugWriteChar);
  cmock_call_instance = (CMOCK_debugWriteChar_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugWriteChar_CallInstance);
  Mock.debugWriteChar_CallInstance = CMock_Guts_MemNext(Mock.debugWriteChar_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_debugWriteChar,CMockString_c);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_c, c, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_debugWriteChar(CMOCK_debugWriteChar_CALL_INSTANCE* cmock_call_instance, uint8_t c)
{
  cmock_call_instance->Expected_c = c;
}

void debugWriteChar_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t c)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugWriteChar_CALL_INSTANCE));
  CMOCK_debugWriteChar_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugWriteChar_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugWriteChar_CallInstance = CMock_Guts_MemChain(Mock.debugWriteChar_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debugWriteChar(cmock_call_instance, c);
  UNITY_CLR_DETAILS();
}

void debugWriteCharBlock(uint8_t c)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugWriteCharBlock_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugWriteCharBlock);
  cmock_call_instance = (CMOCK_debugWriteCharBlock_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugWriteCharBlock_CallInstance);
  Mock.debugWriteCharBlock_CallInstance = CMock_Guts_MemNext(Mock.debugWriteCharBlock_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_debugWriteCharBlock,CMockString_c);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_c, c, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_debugWriteCharBlock(CMOCK_debugWriteCharBlock_CALL_INSTANCE* cmock_call_instance, uint8_t c)
{
  cmock_call_instance->Expected_c = c;
}

void debugWriteCharBlock_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t c)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugWriteCharBlock_CALL_INSTANCE));
  CMOCK_debugWriteCharBlock_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugWriteCharBlock_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugWriteCharBlock_CallInstance = CMock_Guts_MemChain(Mock.debugWriteCharBlock_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debugWriteCharBlock(cmock_call_instance, c);
  UNITY_CLR_DETAILS();
}

void debugWriteCharHelper(uint8_t c, uint8_t last)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugWriteCharHelper_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugWriteCharHelper);
  cmock_call_instance = (CMOCK_debugWriteCharHelper_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugWriteCharHelper_CallInstance);
  Mock.debugWriteCharHelper_CallInstance = CMock_Guts_MemNext(Mock.debugWriteCharHelper_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_debugWriteCharHelper,CMockString_c);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_c, c, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_debugWriteCharHelper,CMockString_last);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_last, last, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_debugWriteCharHelper(CMOCK_debugWriteCharHelper_CALL_INSTANCE* cmock_call_instance, uint8_t c, uint8_t last)
{
  cmock_call_instance->Expected_c = c;
  cmock_call_instance->Expected_last = last;
}

void debugWriteCharHelper_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t c, uint8_t last)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugWriteCharHelper_CALL_INSTANCE));
  CMOCK_debugWriteCharHelper_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugWriteCharHelper_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugWriteCharHelper_CallInstance = CMock_Guts_MemChain(Mock.debugWriteCharHelper_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debugWriteCharHelper(cmock_call_instance, c, last);
  UNITY_CLR_DETAILS();
}

void debugReadChar(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugReadChar_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugReadChar);
  cmock_call_instance = (CMOCK_debugReadChar_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugReadChar_CallInstance);
  Mock.debugReadChar_CallInstance = CMock_Guts_MemNext(Mock.debugReadChar_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void debugReadChar_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugReadChar_CALL_INSTANCE));
  CMOCK_debugReadChar_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugReadChar_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugReadChar_CallInstance = CMock_Guts_MemChain(Mock.debugReadChar_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

uint8_t debugReadCharAvailable(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugReadCharAvailable_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugReadCharAvailable);
  cmock_call_instance = (CMOCK_debugReadCharAvailable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugReadCharAvailable_CallInstance);
  Mock.debugReadCharAvailable_CallInstance = CMock_Guts_MemNext(Mock.debugReadCharAvailable_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void debugReadCharAvailable_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugReadCharAvailable_CALL_INSTANCE));
  CMOCK_debugReadCharAvailable_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugReadCharAvailable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugReadCharAvailable_CallInstance = CMock_Guts_MemChain(Mock.debugReadCharAvailable_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void debugReadCharProcessed(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugReadCharProcessed_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugReadCharProcessed);
  cmock_call_instance = (CMOCK_debugReadCharProcessed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugReadCharProcessed_CallInstance);
  Mock.debugReadCharProcessed_CallInstance = CMock_Guts_MemNext(Mock.debugReadCharProcessed_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void debugReadCharProcessed_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugReadCharProcessed_CALL_INSTANCE));
  CMOCK_debugReadCharProcessed_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugReadCharProcessed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugReadCharProcessed_CallInstance = CMock_Guts_MemChain(Mock.debugReadCharProcessed_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

uint8_t debugGetChar(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugGetChar_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugGetChar);
  cmock_call_instance = (CMOCK_debugGetChar_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugGetChar_CallInstance);
  Mock.debugGetChar_CallInstance = CMock_Guts_MemNext(Mock.debugGetChar_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void debugGetChar_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugGetChar_CALL_INSTANCE));
  CMOCK_debugGetChar_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugGetChar_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugGetChar_CallInstance = CMock_Guts_MemChain(Mock.debugGetChar_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void debugWriteHex8(uint8_t num)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugWriteHex8_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugWriteHex8);
  cmock_call_instance = (CMOCK_debugWriteHex8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugWriteHex8_CallInstance);
  Mock.debugWriteHex8_CallInstance = CMock_Guts_MemNext(Mock.debugWriteHex8_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_debugWriteHex8,CMockString_num);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_num, num, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_debugWriteHex8(CMOCK_debugWriteHex8_CALL_INSTANCE* cmock_call_instance, uint8_t num)
{
  cmock_call_instance->Expected_num = num;
}

void debugWriteHex8_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t num)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugWriteHex8_CALL_INSTANCE));
  CMOCK_debugWriteHex8_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugWriteHex8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugWriteHex8_CallInstance = CMock_Guts_MemChain(Mock.debugWriteHex8_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debugWriteHex8(cmock_call_instance, num);
  UNITY_CLR_DETAILS();
}

void debugWriteHex8Helper(uint8_t num, uint8_t last)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugWriteHex8Helper_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugWriteHex8Helper);
  cmock_call_instance = (CMOCK_debugWriteHex8Helper_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugWriteHex8Helper_CallInstance);
  Mock.debugWriteHex8Helper_CallInstance = CMock_Guts_MemNext(Mock.debugWriteHex8Helper_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_debugWriteHex8Helper,CMockString_num);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_num, num, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_debugWriteHex8Helper,CMockString_last);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_last, last, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_debugWriteHex8Helper(CMOCK_debugWriteHex8Helper_CALL_INSTANCE* cmock_call_instance, uint8_t num, uint8_t last)
{
  cmock_call_instance->Expected_num = num;
  cmock_call_instance->Expected_last = last;
}

void debugWriteHex8Helper_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t num, uint8_t last)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugWriteHex8Helper_CALL_INSTANCE));
  CMOCK_debugWriteHex8Helper_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugWriteHex8Helper_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugWriteHex8Helper_CallInstance = CMock_Guts_MemChain(Mock.debugWriteHex8Helper_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debugWriteHex8Helper(cmock_call_instance, num, last);
  UNITY_CLR_DETAILS();
}

void debugWriteHex16(uint16_t num)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugWriteHex16_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugWriteHex16);
  cmock_call_instance = (CMOCK_debugWriteHex16_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugWriteHex16_CallInstance);
  Mock.debugWriteHex16_CallInstance = CMock_Guts_MemNext(Mock.debugWriteHex16_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_debugWriteHex16,CMockString_num);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_num, num, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_debugWriteHex16(CMOCK_debugWriteHex16_CALL_INSTANCE* cmock_call_instance, uint16_t num)
{
  cmock_call_instance->Expected_num = num;
}

void debugWriteHex16_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t num)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugWriteHex16_CALL_INSTANCE));
  CMOCK_debugWriteHex16_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugWriteHex16_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugWriteHex16_CallInstance = CMock_Guts_MemChain(Mock.debugWriteHex16_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debugWriteHex16(cmock_call_instance, num);
  UNITY_CLR_DETAILS();
}

void debugWriteDec8(uint8_t num)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugWriteDec8_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugWriteDec8);
  cmock_call_instance = (CMOCK_debugWriteDec8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugWriteDec8_CallInstance);
  Mock.debugWriteDec8_CallInstance = CMock_Guts_MemNext(Mock.debugWriteDec8_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_debugWriteDec8,CMockString_num);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_num, num, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_debugWriteDec8(CMOCK_debugWriteDec8_CALL_INSTANCE* cmock_call_instance, uint8_t num)
{
  cmock_call_instance->Expected_num = num;
}

void debugWriteDec8_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t num)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugWriteDec8_CALL_INSTANCE));
  CMOCK_debugWriteDec8_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugWriteDec8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugWriteDec8_CallInstance = CMock_Guts_MemChain(Mock.debugWriteDec8_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debugWriteDec8(cmock_call_instance, num);
  UNITY_CLR_DETAILS();
}

void debugWriteDec16(uint16_t num)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugWriteDec16_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugWriteDec16);
  cmock_call_instance = (CMOCK_debugWriteDec16_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugWriteDec16_CallInstance);
  Mock.debugWriteDec16_CallInstance = CMock_Guts_MemNext(Mock.debugWriteDec16_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_debugWriteDec16,CMockString_num);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_num, num, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_debugWriteDec16(CMOCK_debugWriteDec16_CALL_INSTANCE* cmock_call_instance, uint16_t num)
{
  cmock_call_instance->Expected_num = num;
}

void debugWriteDec16_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t num)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugWriteDec16_CALL_INSTANCE));
  CMOCK_debugWriteDec16_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugWriteDec16_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugWriteDec16_CallInstance = CMock_Guts_MemChain(Mock.debugWriteDec16_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debugWriteDec16(cmock_call_instance, num);
  UNITY_CLR_DETAILS();
}

void debugWriteBin8(uint8_t num)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugWriteBin8_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugWriteBin8);
  cmock_call_instance = (CMOCK_debugWriteBin8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugWriteBin8_CallInstance);
  Mock.debugWriteBin8_CallInstance = CMock_Guts_MemNext(Mock.debugWriteBin8_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_debugWriteBin8,CMockString_num);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_num, num, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_debugWriteBin8(CMOCK_debugWriteBin8_CALL_INSTANCE* cmock_call_instance, uint8_t num)
{
  cmock_call_instance->Expected_num = num;
}

void debugWriteBin8_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t num)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugWriteBin8_CALL_INSTANCE));
  CMOCK_debugWriteBin8_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugWriteBin8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugWriteBin8_CallInstance = CMock_Guts_MemChain(Mock.debugWriteBin8_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debugWriteBin8(cmock_call_instance, num);
  UNITY_CLR_DETAILS();
}

void debugWriteHex32(uint32_t num)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugWriteHex32_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugWriteHex32);
  cmock_call_instance = (CMOCK_debugWriteHex32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugWriteHex32_CallInstance);
  Mock.debugWriteHex32_CallInstance = CMock_Guts_MemNext(Mock.debugWriteHex32_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_debugWriteHex32,CMockString_num);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_num, num, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_debugWriteHex32(CMOCK_debugWriteHex32_CALL_INSTANCE* cmock_call_instance, uint32_t num)
{
  cmock_call_instance->Expected_num = num;
}

void debugWriteHex32_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t num)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugWriteHex32_CALL_INSTANCE));
  CMOCK_debugWriteHex32_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugWriteHex32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugWriteHex32_CallInstance = CMock_Guts_MemChain(Mock.debugWriteHex32_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debugWriteHex32(cmock_call_instance, num);
  UNITY_CLR_DETAILS();
}

void debugWriteBin32(uint32_t num)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugWriteBin32_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugWriteBin32);
  cmock_call_instance = (CMOCK_debugWriteBin32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugWriteBin32_CallInstance);
  Mock.debugWriteBin32_CallInstance = CMock_Guts_MemNext(Mock.debugWriteBin32_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_debugWriteBin32,CMockString_num);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_num, num, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_debugWriteBin32(CMOCK_debugWriteBin32_CALL_INSTANCE* cmock_call_instance, uint32_t num)
{
  cmock_call_instance->Expected_num = num;
}

void debugWriteBin32_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t num)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugWriteBin32_CALL_INSTANCE));
  CMOCK_debugWriteBin32_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugWriteBin32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugWriteBin32_CallInstance = CMock_Guts_MemChain(Mock.debugWriteBin32_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debugWriteBin32(cmock_call_instance, num);
  UNITY_CLR_DETAILS();
}

void debugWriteFloat(float num)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugWriteFloat_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugWriteFloat);
  cmock_call_instance = (CMOCK_debugWriteFloat_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugWriteFloat_CallInstance);
  Mock.debugWriteFloat_CallInstance = CMock_Guts_MemNext(Mock.debugWriteFloat_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_debugWriteFloat,CMockString_num);
    UNITY_TEST_ASSERT_EQUAL_FLOAT(cmock_call_instance->Expected_num, num, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_debugWriteFloat(CMOCK_debugWriteFloat_CALL_INSTANCE* cmock_call_instance, float num)
{
  cmock_call_instance->Expected_num = num;
}

void debugWriteFloat_CMockExpect(UNITY_LINE_TYPE cmock_line, float num)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugWriteFloat_CALL_INSTANCE));
  CMOCK_debugWriteFloat_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugWriteFloat_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugWriteFloat_CallInstance = CMock_Guts_MemChain(Mock.debugWriteFloat_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debugWriteFloat(cmock_call_instance, num);
  UNITY_CLR_DETAILS();
}

void debugWriteFloatFull(float num)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugWriteFloatFull_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugWriteFloatFull);
  cmock_call_instance = (CMOCK_debugWriteFloatFull_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugWriteFloatFull_CallInstance);
  Mock.debugWriteFloatFull_CallInstance = CMock_Guts_MemNext(Mock.debugWriteFloatFull_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_debugWriteFloatFull,CMockString_num);
    UNITY_TEST_ASSERT_EQUAL_FLOAT(cmock_call_instance->Expected_num, num, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_debugWriteFloatFull(CMOCK_debugWriteFloatFull_CALL_INSTANCE* cmock_call_instance, float num)
{
  cmock_call_instance->Expected_num = num;
}

void debugWriteFloatFull_CMockExpect(UNITY_LINE_TYPE cmock_line, float num)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugWriteFloatFull_CALL_INSTANCE));
  CMOCK_debugWriteFloatFull_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugWriteFloatFull_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugWriteFloatFull_CallInstance = CMock_Guts_MemChain(Mock.debugWriteFloatFull_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debugWriteFloatFull(cmock_call_instance, num);
  UNITY_CLR_DETAILS();
}

void debugWriteBin4(uint8_t num)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugWriteBin4_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugWriteBin4);
  cmock_call_instance = (CMOCK_debugWriteBin4_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugWriteBin4_CallInstance);
  Mock.debugWriteBin4_CallInstance = CMock_Guts_MemNext(Mock.debugWriteBin4_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_debugWriteBin4,CMockString_num);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_num, num, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_debugWriteBin4(CMOCK_debugWriteBin4_CALL_INSTANCE* cmock_call_instance, uint8_t num)
{
  cmock_call_instance->Expected_num = num;
}

void debugWriteBin4_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t num)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugWriteBin4_CALL_INSTANCE));
  CMOCK_debugWriteBin4_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugWriteBin4_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugWriteBin4_CallInstance = CMock_Guts_MemChain(Mock.debugWriteBin4_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debugWriteBin4(cmock_call_instance, num);
  UNITY_CLR_DETAILS();
}

void debugWriteDec32(uint32_t num)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugWriteDec32_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugWriteDec32);
  cmock_call_instance = (CMOCK_debugWriteDec32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugWriteDec32_CallInstance);
  Mock.debugWriteDec32_CallInstance = CMock_Guts_MemNext(Mock.debugWriteDec32_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_debugWriteDec32,CMockString_num);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_num, num, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_debugWriteDec32(CMOCK_debugWriteDec32_CALL_INSTANCE* cmock_call_instance, uint32_t num)
{
  cmock_call_instance->Expected_num = num;
}

void debugWriteDec32_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t num)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugWriteDec32_CALL_INSTANCE));
  CMOCK_debugWriteDec32_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugWriteDec32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugWriteDec32_CallInstance = CMock_Guts_MemChain(Mock.debugWriteDec32_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debugWriteDec32(cmock_call_instance, num);
  UNITY_CLR_DETAILS();
}

void debugWriteDec32S(int32_t num)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugWriteDec32S_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugWriteDec32S);
  cmock_call_instance = (CMOCK_debugWriteDec32S_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugWriteDec32S_CallInstance);
  Mock.debugWriteDec32S_CallInstance = CMock_Guts_MemNext(Mock.debugWriteDec32S_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_debugWriteDec32S,CMockString_num);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_num, num, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_debugWriteDec32S(CMOCK_debugWriteDec32S_CALL_INSTANCE* cmock_call_instance, int32_t num)
{
  cmock_call_instance->Expected_num = num;
}

void debugWriteDec32S_CMockExpect(UNITY_LINE_TYPE cmock_line, int32_t num)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugWriteDec32S_CALL_INSTANCE));
  CMOCK_debugWriteDec32S_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugWriteDec32S_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugWriteDec32S_CallInstance = CMock_Guts_MemChain(Mock.debugWriteDec32S_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debugWriteDec32S(cmock_call_instance, num);
  UNITY_CLR_DETAILS();
}

void debugDone(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugDone_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugDone);
  cmock_call_instance = (CMOCK_debugDone_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugDone_CallInstance);
  Mock.debugDone_CallInstance = CMock_Guts_MemNext(Mock.debugDone_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void debugDone_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugDone_CALL_INSTANCE));
  CMOCK_debugDone_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugDone_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugDone_CallInstance = CMock_Guts_MemChain(Mock.debugDone_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void debugReady(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugReady_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugReady);
  cmock_call_instance = (CMOCK_debugReady_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugReady_CallInstance);
  Mock.debugReady_CallInstance = CMock_Guts_MemNext(Mock.debugReady_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void debugReady_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugReady_CALL_INSTANCE));
  CMOCK_debugReady_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugReady_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugReady_CallInstance = CMock_Guts_MemChain(Mock.debugReady_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void debugWaitUntilDone(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugWaitUntilDone_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugWaitUntilDone);
  cmock_call_instance = (CMOCK_debugWaitUntilDone_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugWaitUntilDone_CallInstance);
  Mock.debugWaitUntilDone_CallInstance = CMock_Guts_MemNext(Mock.debugWaitUntilDone_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void debugWaitUntilDone_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugWaitUntilDone_CALL_INSTANCE));
  CMOCK_debugWaitUntilDone_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugWaitUntilDone_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugWaitUntilDone_CallInstance = CMock_Guts_MemChain(Mock.debugWaitUntilDone_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

uint8_t debugSending(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugSending_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugSending);
  cmock_call_instance = (CMOCK_debugSending_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugSending_CallInstance);
  Mock.debugSending_CallInstance = CMock_Guts_MemNext(Mock.debugSending_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void debugSending_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugSending_CALL_INSTANCE));
  CMOCK_debugSending_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugSending_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugSending_CallInstance = CMock_Guts_MemChain(Mock.debugSending_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void debugAck(uint8_t c)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_debugAck_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_debugAck);
  cmock_call_instance = (CMOCK_debugAck_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.debugAck_CallInstance);
  Mock.debugAck_CallInstance = CMock_Guts_MemNext(Mock.debugAck_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_debugAck,CMockString_c);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_c, c, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_debugAck(CMOCK_debugAck_CALL_INSTANCE* cmock_call_instance, uint8_t c)
{
  cmock_call_instance->Expected_c = c;
}

void debugAck_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t c)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_debugAck_CALL_INSTANCE));
  CMOCK_debugAck_CALL_INSTANCE* cmock_call_instance = (CMOCK_debugAck_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.debugAck_CallInstance = CMock_Guts_MemChain(Mock.debugAck_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_debugAck(cmock_call_instance, c);
  UNITY_CLR_DETAILS();
}

void printUartHandler(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_printUartHandler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_printUartHandler);
  cmock_call_instance = (CMOCK_printUartHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.printUartHandler_CallInstance);
  Mock.printUartHandler_CallInstance = CMock_Guts_MemNext(Mock.printUartHandler_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void printUartHandler_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_printUartHandler_CALL_INSTANCE));
  CMOCK_printUartHandler_CALL_INSTANCE* cmock_call_instance = (CMOCK_printUartHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.printUartHandler_CallInstance = CMock_Guts_MemChain(Mock.printUartHandler_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

