#!/usr/bin/env python
"""TODO."""

LIST_INDEX_META    = 0
LIST_INDEX_CURRENT = 1
LIST_INDEX_VOLTAGE = 2
LIST_INDEX_POWER   = 3
MEAS_FORMAT        = 'float'

CNTR_DELIMIT        = '\''
REC_BEGIN_DELIMIT   = '{'
REC_END_DELIMIT     = '}'
VAL_BEGIN_DELIMIT   = '['
VAL_END_DELIMIT     = ']'
SPACE               = ' '

CNTR_INDEX          = 0
CH1_NAME_INDEX      = 1
CH1_CURRENT_INDEX   = 2
CH1_VOLTAGE_INDEX   = 3
CH1_POWER_INDEX     = 4
CH2_NAME_INDEX      = 5
CH2_CURRENT_INDEX   = 6
CH2_VOLTAGE_INDEX   = 7
CH2_POWER_INDEX     = 8

