/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "lib/circular_buffer/Mockcircular_buffer.h"

static const char* CMockString_c = "c";
static const char* CMockString_circBufCount = "circBufCount";
static const char* CMockString_circBufCountObjects = "circBufCountObjects";
static const char* CMockString_circBufFree = "circBufFree";
static const char* CMockString_circBufInit = "circBufInit";
static const char* CMockString_circBufPop = "circBufPop";
static const char* CMockString_circBufPush = "circBufPush";
static const char* CMockString_circBufSpace = "circBufSpace";
static const char* CMockString_data = "data";
static const char* CMockString_size = "size";

typedef struct _CMOCK_circBufInit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  circularBuffer* Expected_c;
  uint16_t Expected_size;
  CEXCEPTION_T ExceptionToThrow;
  int Expected_c_Depth;
  int ReturnThruPtr_c_Used;
  circularBuffer* ReturnThruPtr_c_Val;
  int ReturnThruPtr_c_Size;
  int IgnoreArg_c;
  int IgnoreArg_size;

} CMOCK_circBufInit_CALL_INSTANCE;

typedef struct _CMOCK_circBufFree_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  circularBuffer* Expected_c;
  CEXCEPTION_T ExceptionToThrow;
  int Expected_c_Depth;
  int ReturnThruPtr_c_Used;
  circularBuffer* ReturnThruPtr_c_Val;
  int ReturnThruPtr_c_Size;
  int IgnoreArg_c;

} CMOCK_circBufFree_CALL_INSTANCE;

typedef struct _CMOCK_circBufSpace_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint16_t ReturnVal;
  circularBuffer* Expected_c;
  CEXCEPTION_T ExceptionToThrow;
  int Expected_c_Depth;
  int ReturnThruPtr_c_Used;
  circularBuffer* ReturnThruPtr_c_Val;
  int ReturnThruPtr_c_Size;
  int IgnoreArg_c;

} CMOCK_circBufSpace_CALL_INSTANCE;

typedef struct _CMOCK_circBufCount_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint16_t ReturnVal;
  circularBuffer* Expected_c;
  CEXCEPTION_T ExceptionToThrow;
  int Expected_c_Depth;
  int ReturnThruPtr_c_Used;
  circularBuffer* ReturnThruPtr_c_Val;
  int ReturnThruPtr_c_Size;
  int IgnoreArg_c;

} CMOCK_circBufCount_CALL_INSTANCE;

typedef struct _CMOCK_circBufCountObjects_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint16_t ReturnVal;
  circularBuffer* Expected_c;
  uint16_t Expected_size;
  CEXCEPTION_T ExceptionToThrow;
  int Expected_c_Depth;
  int ReturnThruPtr_c_Used;
  circularBuffer* ReturnThruPtr_c_Val;
  int ReturnThruPtr_c_Size;
  int IgnoreArg_c;
  int IgnoreArg_size;

} CMOCK_circBufCountObjects_CALL_INSTANCE;

typedef struct _CMOCK_circBufPush_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint8_t ReturnVal;
  circularBuffer* Expected_c;
  uint8_t Expected_data;
  CEXCEPTION_T ExceptionToThrow;
  int Expected_c_Depth;
  int ReturnThruPtr_c_Used;
  circularBuffer* ReturnThruPtr_c_Val;
  int ReturnThruPtr_c_Size;
  int IgnoreArg_c;
  int IgnoreArg_data;

} CMOCK_circBufPush_CALL_INSTANCE;

typedef struct _CMOCK_circBufPop_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint8_t ReturnVal;
  circularBuffer* Expected_c;
  uint8_t* Expected_data;
  CEXCEPTION_T ExceptionToThrow;
  int Expected_c_Depth;
  int Expected_data_Depth;
  int ReturnThruPtr_c_Used;
  circularBuffer* ReturnThruPtr_c_Val;
  int ReturnThruPtr_c_Size;
  int ReturnThruPtr_data_Used;
  uint8_t* ReturnThruPtr_data_Val;
  int ReturnThruPtr_data_Size;
  int IgnoreArg_c;
  int IgnoreArg_data;

} CMOCK_circBufPop_CALL_INSTANCE;

static struct Mockcircular_bufferInstance
{
  int circBufInit_IgnoreBool;
  CMOCK_circBufInit_CALLBACK circBufInit_CallbackFunctionPointer;
  int circBufInit_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE circBufInit_CallInstance;
  int circBufFree_IgnoreBool;
  CMOCK_circBufFree_CALLBACK circBufFree_CallbackFunctionPointer;
  int circBufFree_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE circBufFree_CallInstance;
  int circBufSpace_IgnoreBool;
  uint16_t circBufSpace_FinalReturn;
  CMOCK_circBufSpace_CALLBACK circBufSpace_CallbackFunctionPointer;
  int circBufSpace_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE circBufSpace_CallInstance;
  int circBufCount_IgnoreBool;
  uint16_t circBufCount_FinalReturn;
  CMOCK_circBufCount_CALLBACK circBufCount_CallbackFunctionPointer;
  int circBufCount_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE circBufCount_CallInstance;
  int circBufCountObjects_IgnoreBool;
  uint16_t circBufCountObjects_FinalReturn;
  CMOCK_circBufCountObjects_CALLBACK circBufCountObjects_CallbackFunctionPointer;
  int circBufCountObjects_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE circBufCountObjects_CallInstance;
  int circBufPush_IgnoreBool;
  uint8_t circBufPush_FinalReturn;
  CMOCK_circBufPush_CALLBACK circBufPush_CallbackFunctionPointer;
  int circBufPush_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE circBufPush_CallInstance;
  int circBufPop_IgnoreBool;
  uint8_t circBufPop_FinalReturn;
  CMOCK_circBufPop_CALLBACK circBufPop_CallbackFunctionPointer;
  int circBufPop_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE circBufPop_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockcircular_buffer_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.circBufInit_IgnoreBool)
    Mock.circBufInit_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_circBufInit);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.circBufInit_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.circBufInit_CallbackFunctionPointer != NULL)
    Mock.circBufInit_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.circBufFree_IgnoreBool)
    Mock.circBufFree_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_circBufFree);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.circBufFree_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.circBufFree_CallbackFunctionPointer != NULL)
    Mock.circBufFree_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.circBufSpace_IgnoreBool)
    Mock.circBufSpace_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_circBufSpace);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.circBufSpace_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.circBufSpace_CallbackFunctionPointer != NULL)
    Mock.circBufSpace_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.circBufCount_IgnoreBool)
    Mock.circBufCount_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_circBufCount);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.circBufCount_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.circBufCount_CallbackFunctionPointer != NULL)
    Mock.circBufCount_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.circBufCountObjects_IgnoreBool)
    Mock.circBufCountObjects_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_circBufCountObjects);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.circBufCountObjects_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.circBufCountObjects_CallbackFunctionPointer != NULL)
    Mock.circBufCountObjects_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.circBufPush_IgnoreBool)
    Mock.circBufPush_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_circBufPush);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.circBufPush_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.circBufPush_CallbackFunctionPointer != NULL)
    Mock.circBufPush_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.circBufPop_IgnoreBool)
    Mock.circBufPop_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_circBufPop);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.circBufPop_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.circBufPop_CallbackFunctionPointer != NULL)
    Mock.circBufPop_CallInstance = CMOCK_GUTS_NONE;
}

void Mockcircular_buffer_Init(void)
{
  Mockcircular_buffer_Destroy();
}

void Mockcircular_buffer_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.circBufInit_CallbackFunctionPointer = NULL;
  Mock.circBufInit_CallbackCalls = 0;
  Mock.circBufFree_CallbackFunctionPointer = NULL;
  Mock.circBufFree_CallbackCalls = 0;
  Mock.circBufSpace_CallbackFunctionPointer = NULL;
  Mock.circBufSpace_CallbackCalls = 0;
  Mock.circBufCount_CallbackFunctionPointer = NULL;
  Mock.circBufCount_CallbackCalls = 0;
  Mock.circBufCountObjects_CallbackFunctionPointer = NULL;
  Mock.circBufCountObjects_CallbackCalls = 0;
  Mock.circBufPush_CallbackFunctionPointer = NULL;
  Mock.circBufPush_CallbackCalls = 0;
  Mock.circBufPop_CallbackFunctionPointer = NULL;
  Mock.circBufPop_CallbackCalls = 0;
}

void circBufInit(circularBuffer* c, uint16_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_circBufInit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_circBufInit);
  cmock_call_instance = (CMOCK_circBufInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.circBufInit_CallInstance);
  Mock.circBufInit_CallInstance = CMock_Guts_MemNext(Mock.circBufInit_CallInstance);
  if (Mock.circBufInit_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.circBufInit_CallbackFunctionPointer != NULL)
  {
    Mock.circBufInit_CallbackFunctionPointer(c, size, Mock.circBufInit_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_c)
  {
    UNITY_SET_DETAILS(CMockString_circBufInit,CMockString_c);
    if (cmock_call_instance->Expected_c == NULL)
      { UNITY_TEST_ASSERT_NULL(c, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_c), (void*)(c), sizeof(circularBuffer), cmock_call_instance->Expected_c_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_size)
  {
    UNITY_SET_DETAILS(CMockString_circBufInit,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_size, size, cmock_line, CMockStringMismatch);
  }
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  if (cmock_call_instance->ReturnThruPtr_c_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(c, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)c, (void*)cmock_call_instance->ReturnThruPtr_c_Val,
      cmock_call_instance->ReturnThruPtr_c_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_circBufInit(CMOCK_circBufInit_CALL_INSTANCE* cmock_call_instance, circularBuffer* c, int c_Depth, uint16_t size)
{
  cmock_call_instance->Expected_c = c;
  cmock_call_instance->Expected_c_Depth = c_Depth;
  cmock_call_instance->IgnoreArg_c = 0;
  cmock_call_instance->ReturnThruPtr_c_Used = 0;
  cmock_call_instance->Expected_size = size;
  cmock_call_instance->IgnoreArg_size = 0;
}

void circBufInit_CMockIgnore(void)
{
  Mock.circBufInit_IgnoreBool = (int)1;
}

void circBufInit_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufInit_CALL_INSTANCE));
  CMOCK_circBufInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufInit_CallInstance = CMock_Guts_MemChain(Mock.circBufInit_CallInstance, cmock_guts_index);
  Mock.circBufInit_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void circBufInit_CMockExpect(UNITY_LINE_TYPE cmock_line, circularBuffer* c, uint16_t size)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufInit_CALL_INSTANCE));
  CMOCK_circBufInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufInit_CallInstance = CMock_Guts_MemChain(Mock.circBufInit_CallInstance, cmock_guts_index);
  Mock.circBufInit_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_circBufInit(cmock_call_instance, c, 1, size);
  UNITY_CLR_DETAILS();
}

void circBufInit_StubWithCallback(CMOCK_circBufInit_CALLBACK Callback)
{
  Mock.circBufInit_IgnoreBool = (int)0;
  Mock.circBufInit_CallbackFunctionPointer = Callback;
}

void circBufInit_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, circularBuffer* c, uint16_t size, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufInit_CALL_INSTANCE));
  CMOCK_circBufInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufInit_CallInstance = CMock_Guts_MemChain(Mock.circBufInit_CallInstance, cmock_guts_index);
  Mock.circBufInit_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_circBufInit(cmock_call_instance, c, 1, size);
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

void circBufInit_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, circularBuffer* c, int c_Depth, uint16_t size)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufInit_CALL_INSTANCE));
  CMOCK_circBufInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufInit_CallInstance = CMock_Guts_MemChain(Mock.circBufInit_CallInstance, cmock_guts_index);
  Mock.circBufInit_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_circBufInit(cmock_call_instance, c, c_Depth, size);
}

void circBufInit_CMockReturnMemThruPtr_c(UNITY_LINE_TYPE cmock_line, circularBuffer* c, int cmock_size)
{
  CMOCK_circBufInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.circBufInit_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_c_Used = 1;
  cmock_call_instance->ReturnThruPtr_c_Val = c;
  cmock_call_instance->ReturnThruPtr_c_Size = cmock_size;
}

void circBufInit_CMockIgnoreArg_c(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_circBufInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.circBufInit_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_c = 1;
}

void circBufInit_CMockIgnoreArg_size(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_circBufInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.circBufInit_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_size = 1;
}

void circBufFree(circularBuffer* c)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_circBufFree_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_circBufFree);
  cmock_call_instance = (CMOCK_circBufFree_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.circBufFree_CallInstance);
  Mock.circBufFree_CallInstance = CMock_Guts_MemNext(Mock.circBufFree_CallInstance);
  if (Mock.circBufFree_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.circBufFree_CallbackFunctionPointer != NULL)
  {
    Mock.circBufFree_CallbackFunctionPointer(c, Mock.circBufFree_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_c)
  {
    UNITY_SET_DETAILS(CMockString_circBufFree,CMockString_c);
    if (cmock_call_instance->Expected_c == NULL)
      { UNITY_TEST_ASSERT_NULL(c, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_c), (void*)(c), sizeof(circularBuffer), cmock_call_instance->Expected_c_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  if (cmock_call_instance->ReturnThruPtr_c_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(c, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)c, (void*)cmock_call_instance->ReturnThruPtr_c_Val,
      cmock_call_instance->ReturnThruPtr_c_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_circBufFree(CMOCK_circBufFree_CALL_INSTANCE* cmock_call_instance, circularBuffer* c, int c_Depth)
{
  cmock_call_instance->Expected_c = c;
  cmock_call_instance->Expected_c_Depth = c_Depth;
  cmock_call_instance->IgnoreArg_c = 0;
  cmock_call_instance->ReturnThruPtr_c_Used = 0;
}

void circBufFree_CMockIgnore(void)
{
  Mock.circBufFree_IgnoreBool = (int)1;
}

void circBufFree_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufFree_CALL_INSTANCE));
  CMOCK_circBufFree_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufFree_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufFree_CallInstance = CMock_Guts_MemChain(Mock.circBufFree_CallInstance, cmock_guts_index);
  Mock.circBufFree_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void circBufFree_CMockExpect(UNITY_LINE_TYPE cmock_line, circularBuffer* c)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufFree_CALL_INSTANCE));
  CMOCK_circBufFree_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufFree_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufFree_CallInstance = CMock_Guts_MemChain(Mock.circBufFree_CallInstance, cmock_guts_index);
  Mock.circBufFree_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_circBufFree(cmock_call_instance, c, 1);
  UNITY_CLR_DETAILS();
}

void circBufFree_StubWithCallback(CMOCK_circBufFree_CALLBACK Callback)
{
  Mock.circBufFree_IgnoreBool = (int)0;
  Mock.circBufFree_CallbackFunctionPointer = Callback;
}

void circBufFree_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, circularBuffer* c, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufFree_CALL_INSTANCE));
  CMOCK_circBufFree_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufFree_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufFree_CallInstance = CMock_Guts_MemChain(Mock.circBufFree_CallInstance, cmock_guts_index);
  Mock.circBufFree_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_circBufFree(cmock_call_instance, c, 1);
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

void circBufFree_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, circularBuffer* c, int c_Depth)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufFree_CALL_INSTANCE));
  CMOCK_circBufFree_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufFree_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufFree_CallInstance = CMock_Guts_MemChain(Mock.circBufFree_CallInstance, cmock_guts_index);
  Mock.circBufFree_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_circBufFree(cmock_call_instance, c, c_Depth);
}

void circBufFree_CMockReturnMemThruPtr_c(UNITY_LINE_TYPE cmock_line, circularBuffer* c, int cmock_size)
{
  CMOCK_circBufFree_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufFree_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.circBufFree_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_c_Used = 1;
  cmock_call_instance->ReturnThruPtr_c_Val = c;
  cmock_call_instance->ReturnThruPtr_c_Size = cmock_size;
}

void circBufFree_CMockIgnoreArg_c(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_circBufFree_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufFree_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.circBufFree_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_c = 1;
}

uint16_t circBufSpace(circularBuffer* c)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_circBufSpace_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_circBufSpace);
  cmock_call_instance = (CMOCK_circBufSpace_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.circBufSpace_CallInstance);
  Mock.circBufSpace_CallInstance = CMock_Guts_MemNext(Mock.circBufSpace_CallInstance);
  if (Mock.circBufSpace_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.circBufSpace_FinalReturn;
    Mock.circBufSpace_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.circBufSpace_CallbackFunctionPointer != NULL)
  {
    return Mock.circBufSpace_CallbackFunctionPointer(c, Mock.circBufSpace_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_c)
  {
    UNITY_SET_DETAILS(CMockString_circBufSpace,CMockString_c);
    if (cmock_call_instance->Expected_c == NULL)
      { UNITY_TEST_ASSERT_NULL(c, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_c), (void*)(c), sizeof(circularBuffer), cmock_call_instance->Expected_c_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  if (cmock_call_instance->ReturnThruPtr_c_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(c, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)c, (void*)cmock_call_instance->ReturnThruPtr_c_Val,
      cmock_call_instance->ReturnThruPtr_c_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_circBufSpace(CMOCK_circBufSpace_CALL_INSTANCE* cmock_call_instance, circularBuffer* c, int c_Depth)
{
  cmock_call_instance->Expected_c = c;
  cmock_call_instance->Expected_c_Depth = c_Depth;
  cmock_call_instance->IgnoreArg_c = 0;
  cmock_call_instance->ReturnThruPtr_c_Used = 0;
}

void circBufSpace_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufSpace_CALL_INSTANCE));
  CMOCK_circBufSpace_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufSpace_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufSpace_CallInstance = CMock_Guts_MemChain(Mock.circBufSpace_CallInstance, cmock_guts_index);
  Mock.circBufSpace_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.circBufSpace_IgnoreBool = (int)1;
}

void circBufSpace_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufSpace_CALL_INSTANCE));
  CMOCK_circBufSpace_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufSpace_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufSpace_CallInstance = CMock_Guts_MemChain(Mock.circBufSpace_CallInstance, cmock_guts_index);
  Mock.circBufSpace_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void circBufSpace_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, circularBuffer* c, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufSpace_CALL_INSTANCE));
  CMOCK_circBufSpace_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufSpace_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufSpace_CallInstance = CMock_Guts_MemChain(Mock.circBufSpace_CallInstance, cmock_guts_index);
  Mock.circBufSpace_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_circBufSpace(cmock_call_instance, c, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void circBufSpace_StubWithCallback(CMOCK_circBufSpace_CALLBACK Callback)
{
  Mock.circBufSpace_IgnoreBool = (int)0;
  Mock.circBufSpace_CallbackFunctionPointer = Callback;
}

void circBufSpace_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, circularBuffer* c, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufSpace_CALL_INSTANCE));
  CMOCK_circBufSpace_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufSpace_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufSpace_CallInstance = CMock_Guts_MemChain(Mock.circBufSpace_CallInstance, cmock_guts_index);
  Mock.circBufSpace_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_circBufSpace(cmock_call_instance, c, 1);
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

void circBufSpace_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, circularBuffer* c, int c_Depth, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufSpace_CALL_INSTANCE));
  CMOCK_circBufSpace_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufSpace_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufSpace_CallInstance = CMock_Guts_MemChain(Mock.circBufSpace_CallInstance, cmock_guts_index);
  Mock.circBufSpace_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_circBufSpace(cmock_call_instance, c, c_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void circBufSpace_CMockReturnMemThruPtr_c(UNITY_LINE_TYPE cmock_line, circularBuffer* c, int cmock_size)
{
  CMOCK_circBufSpace_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufSpace_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.circBufSpace_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_c_Used = 1;
  cmock_call_instance->ReturnThruPtr_c_Val = c;
  cmock_call_instance->ReturnThruPtr_c_Size = cmock_size;
}

void circBufSpace_CMockIgnoreArg_c(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_circBufSpace_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufSpace_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.circBufSpace_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_c = 1;
}

uint16_t circBufCount(circularBuffer* c)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_circBufCount_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_circBufCount);
  cmock_call_instance = (CMOCK_circBufCount_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.circBufCount_CallInstance);
  Mock.circBufCount_CallInstance = CMock_Guts_MemNext(Mock.circBufCount_CallInstance);
  if (Mock.circBufCount_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.circBufCount_FinalReturn;
    Mock.circBufCount_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.circBufCount_CallbackFunctionPointer != NULL)
  {
    return Mock.circBufCount_CallbackFunctionPointer(c, Mock.circBufCount_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_c)
  {
    UNITY_SET_DETAILS(CMockString_circBufCount,CMockString_c);
    if (cmock_call_instance->Expected_c == NULL)
      { UNITY_TEST_ASSERT_NULL(c, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_c), (void*)(c), sizeof(circularBuffer), cmock_call_instance->Expected_c_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  if (cmock_call_instance->ReturnThruPtr_c_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(c, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)c, (void*)cmock_call_instance->ReturnThruPtr_c_Val,
      cmock_call_instance->ReturnThruPtr_c_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_circBufCount(CMOCK_circBufCount_CALL_INSTANCE* cmock_call_instance, circularBuffer* c, int c_Depth)
{
  cmock_call_instance->Expected_c = c;
  cmock_call_instance->Expected_c_Depth = c_Depth;
  cmock_call_instance->IgnoreArg_c = 0;
  cmock_call_instance->ReturnThruPtr_c_Used = 0;
}

void circBufCount_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufCount_CALL_INSTANCE));
  CMOCK_circBufCount_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufCount_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufCount_CallInstance = CMock_Guts_MemChain(Mock.circBufCount_CallInstance, cmock_guts_index);
  Mock.circBufCount_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.circBufCount_IgnoreBool = (int)1;
}

void circBufCount_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufCount_CALL_INSTANCE));
  CMOCK_circBufCount_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufCount_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufCount_CallInstance = CMock_Guts_MemChain(Mock.circBufCount_CallInstance, cmock_guts_index);
  Mock.circBufCount_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void circBufCount_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, circularBuffer* c, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufCount_CALL_INSTANCE));
  CMOCK_circBufCount_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufCount_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufCount_CallInstance = CMock_Guts_MemChain(Mock.circBufCount_CallInstance, cmock_guts_index);
  Mock.circBufCount_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_circBufCount(cmock_call_instance, c, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void circBufCount_StubWithCallback(CMOCK_circBufCount_CALLBACK Callback)
{
  Mock.circBufCount_IgnoreBool = (int)0;
  Mock.circBufCount_CallbackFunctionPointer = Callback;
}

void circBufCount_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, circularBuffer* c, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufCount_CALL_INSTANCE));
  CMOCK_circBufCount_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufCount_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufCount_CallInstance = CMock_Guts_MemChain(Mock.circBufCount_CallInstance, cmock_guts_index);
  Mock.circBufCount_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_circBufCount(cmock_call_instance, c, 1);
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

void circBufCount_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, circularBuffer* c, int c_Depth, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufCount_CALL_INSTANCE));
  CMOCK_circBufCount_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufCount_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufCount_CallInstance = CMock_Guts_MemChain(Mock.circBufCount_CallInstance, cmock_guts_index);
  Mock.circBufCount_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_circBufCount(cmock_call_instance, c, c_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void circBufCount_CMockReturnMemThruPtr_c(UNITY_LINE_TYPE cmock_line, circularBuffer* c, int cmock_size)
{
  CMOCK_circBufCount_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufCount_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.circBufCount_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_c_Used = 1;
  cmock_call_instance->ReturnThruPtr_c_Val = c;
  cmock_call_instance->ReturnThruPtr_c_Size = cmock_size;
}

void circBufCount_CMockIgnoreArg_c(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_circBufCount_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufCount_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.circBufCount_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_c = 1;
}

uint16_t circBufCountObjects(circularBuffer* c, uint16_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_circBufCountObjects_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_circBufCountObjects);
  cmock_call_instance = (CMOCK_circBufCountObjects_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.circBufCountObjects_CallInstance);
  Mock.circBufCountObjects_CallInstance = CMock_Guts_MemNext(Mock.circBufCountObjects_CallInstance);
  if (Mock.circBufCountObjects_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.circBufCountObjects_FinalReturn;
    Mock.circBufCountObjects_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.circBufCountObjects_CallbackFunctionPointer != NULL)
  {
    return Mock.circBufCountObjects_CallbackFunctionPointer(c, size, Mock.circBufCountObjects_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_c)
  {
    UNITY_SET_DETAILS(CMockString_circBufCountObjects,CMockString_c);
    if (cmock_call_instance->Expected_c == NULL)
      { UNITY_TEST_ASSERT_NULL(c, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_c), (void*)(c), sizeof(circularBuffer), cmock_call_instance->Expected_c_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_size)
  {
    UNITY_SET_DETAILS(CMockString_circBufCountObjects,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_size, size, cmock_line, CMockStringMismatch);
  }
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  if (cmock_call_instance->ReturnThruPtr_c_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(c, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)c, (void*)cmock_call_instance->ReturnThruPtr_c_Val,
      cmock_call_instance->ReturnThruPtr_c_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_circBufCountObjects(CMOCK_circBufCountObjects_CALL_INSTANCE* cmock_call_instance, circularBuffer* c, int c_Depth, uint16_t size)
{
  cmock_call_instance->Expected_c = c;
  cmock_call_instance->Expected_c_Depth = c_Depth;
  cmock_call_instance->IgnoreArg_c = 0;
  cmock_call_instance->ReturnThruPtr_c_Used = 0;
  cmock_call_instance->Expected_size = size;
  cmock_call_instance->IgnoreArg_size = 0;
}

void circBufCountObjects_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufCountObjects_CALL_INSTANCE));
  CMOCK_circBufCountObjects_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufCountObjects_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufCountObjects_CallInstance = CMock_Guts_MemChain(Mock.circBufCountObjects_CallInstance, cmock_guts_index);
  Mock.circBufCountObjects_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.circBufCountObjects_IgnoreBool = (int)1;
}

void circBufCountObjects_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufCountObjects_CALL_INSTANCE));
  CMOCK_circBufCountObjects_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufCountObjects_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufCountObjects_CallInstance = CMock_Guts_MemChain(Mock.circBufCountObjects_CallInstance, cmock_guts_index);
  Mock.circBufCountObjects_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void circBufCountObjects_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, circularBuffer* c, uint16_t size, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufCountObjects_CALL_INSTANCE));
  CMOCK_circBufCountObjects_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufCountObjects_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufCountObjects_CallInstance = CMock_Guts_MemChain(Mock.circBufCountObjects_CallInstance, cmock_guts_index);
  Mock.circBufCountObjects_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_circBufCountObjects(cmock_call_instance, c, 1, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void circBufCountObjects_StubWithCallback(CMOCK_circBufCountObjects_CALLBACK Callback)
{
  Mock.circBufCountObjects_IgnoreBool = (int)0;
  Mock.circBufCountObjects_CallbackFunctionPointer = Callback;
}

void circBufCountObjects_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, circularBuffer* c, uint16_t size, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufCountObjects_CALL_INSTANCE));
  CMOCK_circBufCountObjects_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufCountObjects_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufCountObjects_CallInstance = CMock_Guts_MemChain(Mock.circBufCountObjects_CallInstance, cmock_guts_index);
  Mock.circBufCountObjects_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_circBufCountObjects(cmock_call_instance, c, 1, size);
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

void circBufCountObjects_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, circularBuffer* c, int c_Depth, uint16_t size, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufCountObjects_CALL_INSTANCE));
  CMOCK_circBufCountObjects_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufCountObjects_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufCountObjects_CallInstance = CMock_Guts_MemChain(Mock.circBufCountObjects_CallInstance, cmock_guts_index);
  Mock.circBufCountObjects_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_circBufCountObjects(cmock_call_instance, c, c_Depth, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void circBufCountObjects_CMockReturnMemThruPtr_c(UNITY_LINE_TYPE cmock_line, circularBuffer* c, int cmock_size)
{
  CMOCK_circBufCountObjects_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufCountObjects_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.circBufCountObjects_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_c_Used = 1;
  cmock_call_instance->ReturnThruPtr_c_Val = c;
  cmock_call_instance->ReturnThruPtr_c_Size = cmock_size;
}

void circBufCountObjects_CMockIgnoreArg_c(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_circBufCountObjects_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufCountObjects_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.circBufCountObjects_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_c = 1;
}

void circBufCountObjects_CMockIgnoreArg_size(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_circBufCountObjects_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufCountObjects_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.circBufCountObjects_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_size = 1;
}

uint8_t circBufPush(circularBuffer* c, uint8_t data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_circBufPush_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_circBufPush);
  cmock_call_instance = (CMOCK_circBufPush_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.circBufPush_CallInstance);
  Mock.circBufPush_CallInstance = CMock_Guts_MemNext(Mock.circBufPush_CallInstance);
  if (Mock.circBufPush_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.circBufPush_FinalReturn;
    Mock.circBufPush_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.circBufPush_CallbackFunctionPointer != NULL)
  {
    return Mock.circBufPush_CallbackFunctionPointer(c, data, Mock.circBufPush_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_c)
  {
    UNITY_SET_DETAILS(CMockString_circBufPush,CMockString_c);
    if (cmock_call_instance->Expected_c == NULL)
      { UNITY_TEST_ASSERT_NULL(c, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_c), (void*)(c), sizeof(circularBuffer), cmock_call_instance->Expected_c_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_data)
  {
    UNITY_SET_DETAILS(CMockString_circBufPush,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_data, data, cmock_line, CMockStringMismatch);
  }
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  if (cmock_call_instance->ReturnThruPtr_c_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(c, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)c, (void*)cmock_call_instance->ReturnThruPtr_c_Val,
      cmock_call_instance->ReturnThruPtr_c_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_circBufPush(CMOCK_circBufPush_CALL_INSTANCE* cmock_call_instance, circularBuffer* c, int c_Depth, uint8_t data)
{
  cmock_call_instance->Expected_c = c;
  cmock_call_instance->Expected_c_Depth = c_Depth;
  cmock_call_instance->IgnoreArg_c = 0;
  cmock_call_instance->ReturnThruPtr_c_Used = 0;
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->IgnoreArg_data = 0;
}

void circBufPush_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufPush_CALL_INSTANCE));
  CMOCK_circBufPush_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufPush_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufPush_CallInstance = CMock_Guts_MemChain(Mock.circBufPush_CallInstance, cmock_guts_index);
  Mock.circBufPush_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.circBufPush_IgnoreBool = (int)1;
}

void circBufPush_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufPush_CALL_INSTANCE));
  CMOCK_circBufPush_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufPush_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufPush_CallInstance = CMock_Guts_MemChain(Mock.circBufPush_CallInstance, cmock_guts_index);
  Mock.circBufPush_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void circBufPush_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, circularBuffer* c, uint8_t data, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufPush_CALL_INSTANCE));
  CMOCK_circBufPush_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufPush_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufPush_CallInstance = CMock_Guts_MemChain(Mock.circBufPush_CallInstance, cmock_guts_index);
  Mock.circBufPush_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_circBufPush(cmock_call_instance, c, 1, data);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void circBufPush_StubWithCallback(CMOCK_circBufPush_CALLBACK Callback)
{
  Mock.circBufPush_IgnoreBool = (int)0;
  Mock.circBufPush_CallbackFunctionPointer = Callback;
}

void circBufPush_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, circularBuffer* c, uint8_t data, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufPush_CALL_INSTANCE));
  CMOCK_circBufPush_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufPush_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufPush_CallInstance = CMock_Guts_MemChain(Mock.circBufPush_CallInstance, cmock_guts_index);
  Mock.circBufPush_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_circBufPush(cmock_call_instance, c, 1, data);
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

void circBufPush_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, circularBuffer* c, int c_Depth, uint8_t data, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufPush_CALL_INSTANCE));
  CMOCK_circBufPush_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufPush_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufPush_CallInstance = CMock_Guts_MemChain(Mock.circBufPush_CallInstance, cmock_guts_index);
  Mock.circBufPush_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_circBufPush(cmock_call_instance, c, c_Depth, data);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void circBufPush_CMockReturnMemThruPtr_c(UNITY_LINE_TYPE cmock_line, circularBuffer* c, int cmock_size)
{
  CMOCK_circBufPush_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufPush_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.circBufPush_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_c_Used = 1;
  cmock_call_instance->ReturnThruPtr_c_Val = c;
  cmock_call_instance->ReturnThruPtr_c_Size = cmock_size;
}

void circBufPush_CMockIgnoreArg_c(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_circBufPush_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufPush_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.circBufPush_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_c = 1;
}

void circBufPush_CMockIgnoreArg_data(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_circBufPush_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufPush_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.circBufPush_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_data = 1;
}

uint8_t circBufPop(circularBuffer* c, uint8_t* data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_circBufPop_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_circBufPop);
  cmock_call_instance = (CMOCK_circBufPop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.circBufPop_CallInstance);
  Mock.circBufPop_CallInstance = CMock_Guts_MemNext(Mock.circBufPop_CallInstance);
  if (Mock.circBufPop_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.circBufPop_FinalReturn;
    Mock.circBufPop_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.circBufPop_CallbackFunctionPointer != NULL)
  {
    return Mock.circBufPop_CallbackFunctionPointer(c, data, Mock.circBufPop_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_c)
  {
    UNITY_SET_DETAILS(CMockString_circBufPop,CMockString_c);
    if (cmock_call_instance->Expected_c == NULL)
      { UNITY_TEST_ASSERT_NULL(c, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_c), (void*)(c), sizeof(circularBuffer), cmock_call_instance->Expected_c_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_data)
  {
    UNITY_SET_DETAILS(CMockString_circBufPop,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_data, data, cmock_call_instance->Expected_data_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  if (cmock_call_instance->ReturnThruPtr_c_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(c, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)c, (void*)cmock_call_instance->ReturnThruPtr_c_Val,
      cmock_call_instance->ReturnThruPtr_c_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_data_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(data, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)data, (void*)cmock_call_instance->ReturnThruPtr_data_Val,
      cmock_call_instance->ReturnThruPtr_data_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_circBufPop(CMOCK_circBufPop_CALL_INSTANCE* cmock_call_instance, circularBuffer* c, int c_Depth, uint8_t* data, int data_Depth)
{
  cmock_call_instance->Expected_c = c;
  cmock_call_instance->Expected_c_Depth = c_Depth;
  cmock_call_instance->IgnoreArg_c = 0;
  cmock_call_instance->ReturnThruPtr_c_Used = 0;
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->Expected_data_Depth = data_Depth;
  cmock_call_instance->IgnoreArg_data = 0;
  cmock_call_instance->ReturnThruPtr_data_Used = 0;
}

void circBufPop_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufPop_CALL_INSTANCE));
  CMOCK_circBufPop_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufPop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufPop_CallInstance = CMock_Guts_MemChain(Mock.circBufPop_CallInstance, cmock_guts_index);
  Mock.circBufPop_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.circBufPop_IgnoreBool = (int)1;
}

void circBufPop_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufPop_CALL_INSTANCE));
  CMOCK_circBufPop_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufPop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufPop_CallInstance = CMock_Guts_MemChain(Mock.circBufPop_CallInstance, cmock_guts_index);
  Mock.circBufPop_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void circBufPop_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, circularBuffer* c, uint8_t* data, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufPop_CALL_INSTANCE));
  CMOCK_circBufPop_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufPop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufPop_CallInstance = CMock_Guts_MemChain(Mock.circBufPop_CallInstance, cmock_guts_index);
  Mock.circBufPop_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_circBufPop(cmock_call_instance, c, 1, data, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void circBufPop_StubWithCallback(CMOCK_circBufPop_CALLBACK Callback)
{
  Mock.circBufPop_IgnoreBool = (int)0;
  Mock.circBufPop_CallbackFunctionPointer = Callback;
}

void circBufPop_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, circularBuffer* c, uint8_t* data, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufPop_CALL_INSTANCE));
  CMOCK_circBufPop_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufPop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufPop_CallInstance = CMock_Guts_MemChain(Mock.circBufPop_CallInstance, cmock_guts_index);
  Mock.circBufPop_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_circBufPop(cmock_call_instance, c, 1, data, 1);
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

void circBufPop_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, circularBuffer* c, int c_Depth, uint8_t* data, int data_Depth, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_circBufPop_CALL_INSTANCE));
  CMOCK_circBufPop_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufPop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.circBufPop_CallInstance = CMock_Guts_MemChain(Mock.circBufPop_CallInstance, cmock_guts_index);
  Mock.circBufPop_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_circBufPop(cmock_call_instance, c, c_Depth, data, data_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void circBufPop_CMockReturnMemThruPtr_c(UNITY_LINE_TYPE cmock_line, circularBuffer* c, int cmock_size)
{
  CMOCK_circBufPop_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufPop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.circBufPop_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_c_Used = 1;
  cmock_call_instance->ReturnThruPtr_c_Val = c;
  cmock_call_instance->ReturnThruPtr_c_Size = cmock_size;
}

void circBufPop_CMockReturnMemThruPtr_data(UNITY_LINE_TYPE cmock_line, uint8_t* data, int cmock_size)
{
  CMOCK_circBufPop_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufPop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.circBufPop_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_data_Used = 1;
  cmock_call_instance->ReturnThruPtr_data_Val = data;
  cmock_call_instance->ReturnThruPtr_data_Size = cmock_size;
}

void circBufPop_CMockIgnoreArg_c(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_circBufPop_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufPop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.circBufPop_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_c = 1;
}

void circBufPop_CMockIgnoreArg_data(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_circBufPop_CALL_INSTANCE* cmock_call_instance = (CMOCK_circBufPop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.circBufPop_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_data = 1;
}

