/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _DELAY_H
#define _DELAY_H

#include "unity.h"
#include "delay.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockdelay_Init(void);
void Mockdelay_Destroy(void);
void Mockdelay_Verify(void);




#define _delay_us_ExpectAndReturn(__us, cmock_retval) _delay_us_CMockExpectAndReturn(__LINE__, __us, cmock_retval)
void _delay_us_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, double __us, __inline__ void cmock_to_return);
#define _delay_ms_ExpectAndReturn(__ms, cmock_retval) _delay_ms_CMockExpectAndReturn(__LINE__, __ms, cmock_retval)
void _delay_ms_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, double __ms, __inline__ void cmock_to_return);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
