/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "twi.h"


static struct MocktwiInstance
{
  unsigned char placeHolder;
} Mock;

extern jmp_buf AbortFrame;

void Mocktwi_Verify(void)
{
}

void Mocktwi_Init(void)
{
  Mocktwi_Destroy();
}

void Mocktwi_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

