/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "interrupt.h"


static struct MockinterruptInstance
{
  unsigned char placeHolder;
} Mock;

extern jmp_buf AbortFrame;

void Mockinterrupt_Verify(void)
{
}

void Mockinterrupt_Init(void)
{
  Mockinterrupt_Destroy();
}

void Mockinterrupt_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

