/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "iom32u4.h"


static struct Mockiom32u4Instance
{
  unsigned char placeHolder;
} Mock;

extern jmp_buf AbortFrame;

void Mockiom32u4_Verify(void)
{
}

void Mockiom32u4_Init(void)
{
  Mockiom32u4_Destroy();
}

void Mockiom32u4_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

