/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "lib/delay/Mockuser_delay.h"

static const char* CMockString_period = "period";
static const char* CMockString_user_delay_ms = "user_delay_ms";

typedef struct _CMOCK_user_delay_ms_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint32_t Expected_period;
  CEXCEPTION_T ExceptionToThrow;
  int IgnoreArg_period;

} CMOCK_user_delay_ms_CALL_INSTANCE;

static struct Mockuser_delayInstance
{
  int user_delay_ms_IgnoreBool;
  CMOCK_user_delay_ms_CALLBACK user_delay_ms_CallbackFunctionPointer;
  int user_delay_ms_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE user_delay_ms_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockuser_delay_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.user_delay_ms_IgnoreBool)
    Mock.user_delay_ms_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_user_delay_ms);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.user_delay_ms_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.user_delay_ms_CallbackFunctionPointer != NULL)
    Mock.user_delay_ms_CallInstance = CMOCK_GUTS_NONE;
}

void Mockuser_delay_Init(void)
{
  Mockuser_delay_Destroy();
}

void Mockuser_delay_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.user_delay_ms_CallbackFunctionPointer = NULL;
  Mock.user_delay_ms_CallbackCalls = 0;
}

void user_delay_ms(uint32_t period)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_user_delay_ms_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_user_delay_ms);
  cmock_call_instance = (CMOCK_user_delay_ms_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.user_delay_ms_CallInstance);
  Mock.user_delay_ms_CallInstance = CMock_Guts_MemNext(Mock.user_delay_ms_CallInstance);
  if (Mock.user_delay_ms_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.user_delay_ms_CallbackFunctionPointer != NULL)
  {
    Mock.user_delay_ms_CallbackFunctionPointer(period, Mock.user_delay_ms_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_period)
  {
    UNITY_SET_DETAILS(CMockString_user_delay_ms,CMockString_period);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_period, period, cmock_line, CMockStringMismatch);
  }
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_user_delay_ms(CMOCK_user_delay_ms_CALL_INSTANCE* cmock_call_instance, uint32_t period)
{
  cmock_call_instance->Expected_period = period;
  cmock_call_instance->IgnoreArg_period = 0;
}

void user_delay_ms_CMockIgnore(void)
{
  Mock.user_delay_ms_IgnoreBool = (int)1;
}

void user_delay_ms_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_user_delay_ms_CALL_INSTANCE));
  CMOCK_user_delay_ms_CALL_INSTANCE* cmock_call_instance = (CMOCK_user_delay_ms_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.user_delay_ms_CallInstance = CMock_Guts_MemChain(Mock.user_delay_ms_CallInstance, cmock_guts_index);
  Mock.user_delay_ms_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void user_delay_ms_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t period)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_user_delay_ms_CALL_INSTANCE));
  CMOCK_user_delay_ms_CALL_INSTANCE* cmock_call_instance = (CMOCK_user_delay_ms_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.user_delay_ms_CallInstance = CMock_Guts_MemChain(Mock.user_delay_ms_CallInstance, cmock_guts_index);
  Mock.user_delay_ms_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_user_delay_ms(cmock_call_instance, period);
  UNITY_CLR_DETAILS();
}

void user_delay_ms_StubWithCallback(CMOCK_user_delay_ms_CALLBACK Callback)
{
  Mock.user_delay_ms_IgnoreBool = (int)0;
  Mock.user_delay_ms_CallbackFunctionPointer = Callback;
}

void user_delay_ms_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, uint32_t period, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_user_delay_ms_CALL_INSTANCE));
  CMOCK_user_delay_ms_CALL_INSTANCE* cmock_call_instance = (CMOCK_user_delay_ms_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.user_delay_ms_CallInstance = CMock_Guts_MemChain(Mock.user_delay_ms_CallInstance, cmock_guts_index);
  Mock.user_delay_ms_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_user_delay_ms(cmock_call_instance, period);
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

void user_delay_ms_CMockIgnoreArg_period(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_user_delay_ms_CALL_INSTANCE* cmock_call_instance = (CMOCK_user_delay_ms_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.user_delay_ms_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_period = 1;
}

