/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockcurrent_sense.h"

static const char* CMockString_address = "address";
static const char* CMockString_c = "c";
static const char* CMockString_channel = "channel";
static const char* CMockString_currentSenseBegin = "currentSenseBegin";
static const char* CMockString_currentSenseClearMeasurements = "currentSenseClearMeasurements";
static const char* CMockString_currentSenseConfig = "currentSenseConfig";
static const char* CMockString_currentSenseConvert = "currentSenseConvert";
static const char* CMockString_currentSenseCount = "currentSenseCount";
static const char* CMockString_currentSenseEnd = "currentSenseEnd";
static const char* CMockString_currentSensePushMeasurements = "currentSensePushMeasurements";
static const char* CMockString_currentSenseStartAll = "currentSenseStartAll";
static const char* CMockString_currentSenseTask = "currentSenseTask";
static const char* CMockString_device = "device";
static const char* CMockString_fetchCurrent = "fetchCurrent";
static const char* CMockString_fetchCurrentMeasurementFloat = "fetchCurrentMeasurementFloat";
static const char* CMockString_findCurrentSensors = "findCurrentSensors";
static const char* CMockString_getAddress = "getAddress";
static const char* CMockString_initCurrentSense = "initCurrentSense";
static const char* CMockString_printAccID = "printAccID";
static const char* CMockString_printAccelerometerValues = "printAccelerometerValues";
static const char* CMockString_printAllCurrentMeasurementsFloat = "printAllCurrentMeasurementsFloat";
static const char* CMockString_printCurrent = "printCurrent";
static const char* CMockString_printCurrentMeasurement = "printCurrentMeasurement";
static const char* CMockString_printCurrentMeasurementFloat = "printCurrentMeasurementFloat";
static const char* CMockString_printCurrentProductId = "printCurrentProductId";
static const char* CMockString_printCurrentSense = "printCurrentSense";
static const char* CMockString_push = "push";
static const char* CMockString_readCurrentSense = "readCurrentSense";
static const char* CMockString_readCurrentSenseBlocking = "readCurrentSenseBlocking";
static const char* CMockString_register_address = "register_address";
static const char* CMockString_sense = "sense";
static const char* CMockString_value = "value";
static const char* CMockString_writeRegister = "writeRegister";

typedef struct _CMOCK_initCurrentSense_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_initCurrentSense_CALL_INSTANCE;

typedef struct _CMOCK_currentSenseConfig_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_currentSenseConfig_CALL_INSTANCE;

typedef struct _CMOCK_currentSensePushMeasurements_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t Expected_push;

} CMOCK_currentSensePushMeasurements_CALL_INSTANCE;

typedef struct _CMOCK_findCurrentSensors_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_findCurrentSensors_CALL_INSTANCE;

typedef struct _CMOCK_currentSenseCount_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_currentSenseCount_CALL_INSTANCE;

typedef struct _CMOCK_currentSenseBegin_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_currentSenseBegin_CALL_INSTANCE;

typedef struct _CMOCK_currentSenseEnd_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_currentSenseEnd_CALL_INSTANCE;

typedef struct _CMOCK_currentSenseTask_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;

} CMOCK_currentSenseTask_CALL_INSTANCE;

typedef struct _CMOCK_getAddress_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;
  uint8_t Expected_device;

} CMOCK_getAddress_CALL_INSTANCE;

typedef struct _CMOCK_writeRegister_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t Expected_address;
  uint8_t Expected_register_address;
  uint8_t Expected_value;

} CMOCK_writeRegister_CALL_INSTANCE;

typedef struct _CMOCK_currentSenseClearMeasurements_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_currentSenseClearMeasurements_CALL_INSTANCE;

typedef struct _CMOCK_printAccID_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_printAccID_CALL_INSTANCE;

typedef struct _CMOCK_printCurrentProductId_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t Expected_address;

} CMOCK_printCurrentProductId_CALL_INSTANCE;

typedef struct _CMOCK_currentSenseConvert_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  float ReturnVal;
  uint8_t Expected_device;
  uint16_t Expected_sense;

} CMOCK_currentSenseConvert_CALL_INSTANCE;

typedef struct _CMOCK_printCurrent_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t Expected_device;

} CMOCK_printCurrent_CALL_INSTANCE;

typedef struct _CMOCK_printAccelerometerValues_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_printAccelerometerValues_CALL_INSTANCE;

typedef struct _CMOCK_readCurrentSense_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;
  uint8_t Expected_address;
  uint8_t Expected_channel;

} CMOCK_readCurrentSense_CALL_INSTANCE;

typedef struct _CMOCK_readCurrentSenseBlocking_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t ReturnVal;
  uint8_t Expected_address;
  uint8_t Expected_channel;

} CMOCK_readCurrentSenseBlocking_CALL_INSTANCE;

typedef struct _CMOCK_printCurrentSense_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t Expected_address;
  uint8_t Expected_channel;

} CMOCK_printCurrentSense_CALL_INSTANCE;

typedef struct _CMOCK_printCurrentMeasurement_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  currentMeasurement Expected_c;

} CMOCK_printCurrentMeasurement_CALL_INSTANCE;

typedef struct _CMOCK_printCurrentMeasurementFloat_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  currentMeasurementFloat Expected_c;

} CMOCK_printCurrentMeasurementFloat_CALL_INSTANCE;

typedef struct _CMOCK_printAllCurrentMeasurementsFloat_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_printAllCurrentMeasurementsFloat_CALL_INSTANCE;

typedef struct _CMOCK_fetchCurrent_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  float ReturnVal;
  uint8_t Expected_device;

} CMOCK_fetchCurrent_CALL_INSTANCE;

typedef struct _CMOCK_fetchCurrentMeasurementFloat_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  currentMeasurementFloat ReturnVal;

} CMOCK_fetchCurrentMeasurementFloat_CALL_INSTANCE;

typedef struct _CMOCK_currentSenseStartAll_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_currentSenseStartAll_CALL_INSTANCE;

static struct Mockcurrent_senseInstance
{
  CMOCK_MEM_INDEX_TYPE initCurrentSense_CallInstance;
  CMOCK_MEM_INDEX_TYPE currentSenseConfig_CallInstance;
  CMOCK_MEM_INDEX_TYPE currentSensePushMeasurements_CallInstance;
  CMOCK_MEM_INDEX_TYPE findCurrentSensors_CallInstance;
  CMOCK_MEM_INDEX_TYPE currentSenseCount_CallInstance;
  CMOCK_MEM_INDEX_TYPE currentSenseBegin_CallInstance;
  CMOCK_MEM_INDEX_TYPE currentSenseEnd_CallInstance;
  CMOCK_MEM_INDEX_TYPE currentSenseTask_CallInstance;
  CMOCK_MEM_INDEX_TYPE getAddress_CallInstance;
  CMOCK_MEM_INDEX_TYPE writeRegister_CallInstance;
  CMOCK_MEM_INDEX_TYPE currentSenseClearMeasurements_CallInstance;
  CMOCK_MEM_INDEX_TYPE printAccID_CallInstance;
  CMOCK_MEM_INDEX_TYPE printCurrentProductId_CallInstance;
  CMOCK_MEM_INDEX_TYPE currentSenseConvert_CallInstance;
  CMOCK_MEM_INDEX_TYPE printCurrent_CallInstance;
  CMOCK_MEM_INDEX_TYPE printAccelerometerValues_CallInstance;
  CMOCK_MEM_INDEX_TYPE readCurrentSense_CallInstance;
  CMOCK_MEM_INDEX_TYPE readCurrentSenseBlocking_CallInstance;
  CMOCK_MEM_INDEX_TYPE printCurrentSense_CallInstance;
  CMOCK_MEM_INDEX_TYPE printCurrentMeasurement_CallInstance;
  CMOCK_MEM_INDEX_TYPE printCurrentMeasurementFloat_CallInstance;
  CMOCK_MEM_INDEX_TYPE printAllCurrentMeasurementsFloat_CallInstance;
  CMOCK_MEM_INDEX_TYPE fetchCurrent_CallInstance;
  CMOCK_MEM_INDEX_TYPE fetchCurrentMeasurementFloat_CallInstance;
  CMOCK_MEM_INDEX_TYPE currentSenseStartAll_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockcurrent_sense_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_initCurrentSense);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.initCurrentSense_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_currentSenseConfig);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.currentSenseConfig_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_currentSensePushMeasurements);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.currentSensePushMeasurements_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_findCurrentSensors);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.findCurrentSensors_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_currentSenseCount);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.currentSenseCount_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_currentSenseBegin);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.currentSenseBegin_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_currentSenseEnd);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.currentSenseEnd_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_currentSenseTask);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.currentSenseTask_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_getAddress);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.getAddress_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_writeRegister);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.writeRegister_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_currentSenseClearMeasurements);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.currentSenseClearMeasurements_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_printAccID);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.printAccID_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_printCurrentProductId);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.printCurrentProductId_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_currentSenseConvert);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.currentSenseConvert_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_printCurrent);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.printCurrent_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_printAccelerometerValues);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.printAccelerometerValues_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_readCurrentSense);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.readCurrentSense_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_readCurrentSenseBlocking);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.readCurrentSenseBlocking_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_printCurrentSense);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.printCurrentSense_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_printCurrentMeasurement);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.printCurrentMeasurement_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_printCurrentMeasurementFloat);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.printCurrentMeasurementFloat_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_printAllCurrentMeasurementsFloat);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.printAllCurrentMeasurementsFloat_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_fetchCurrent);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.fetchCurrent_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_fetchCurrentMeasurementFloat);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.fetchCurrentMeasurementFloat_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_currentSenseStartAll);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.currentSenseStartAll_CallInstance, cmock_line, CMockStringCalledLess);
}

void Mockcurrent_sense_Init(void)
{
  Mockcurrent_sense_Destroy();
}

void Mockcurrent_sense_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void initCurrentSense(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_initCurrentSense_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_initCurrentSense);
  cmock_call_instance = (CMOCK_initCurrentSense_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.initCurrentSense_CallInstance);
  Mock.initCurrentSense_CallInstance = CMock_Guts_MemNext(Mock.initCurrentSense_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void initCurrentSense_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_initCurrentSense_CALL_INSTANCE));
  CMOCK_initCurrentSense_CALL_INSTANCE* cmock_call_instance = (CMOCK_initCurrentSense_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.initCurrentSense_CallInstance = CMock_Guts_MemChain(Mock.initCurrentSense_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void currentSenseConfig(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_currentSenseConfig_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_currentSenseConfig);
  cmock_call_instance = (CMOCK_currentSenseConfig_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.currentSenseConfig_CallInstance);
  Mock.currentSenseConfig_CallInstance = CMock_Guts_MemNext(Mock.currentSenseConfig_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void currentSenseConfig_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_currentSenseConfig_CALL_INSTANCE));
  CMOCK_currentSenseConfig_CALL_INSTANCE* cmock_call_instance = (CMOCK_currentSenseConfig_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.currentSenseConfig_CallInstance = CMock_Guts_MemChain(Mock.currentSenseConfig_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void currentSensePushMeasurements(uint8_t push)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_currentSensePushMeasurements_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_currentSensePushMeasurements);
  cmock_call_instance = (CMOCK_currentSensePushMeasurements_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.currentSensePushMeasurements_CallInstance);
  Mock.currentSensePushMeasurements_CallInstance = CMock_Guts_MemNext(Mock.currentSensePushMeasurements_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_currentSensePushMeasurements,CMockString_push);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_push, push, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_currentSensePushMeasurements(CMOCK_currentSensePushMeasurements_CALL_INSTANCE* cmock_call_instance, uint8_t push)
{
  cmock_call_instance->Expected_push = push;
}

void currentSensePushMeasurements_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t push)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_currentSensePushMeasurements_CALL_INSTANCE));
  CMOCK_currentSensePushMeasurements_CALL_INSTANCE* cmock_call_instance = (CMOCK_currentSensePushMeasurements_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.currentSensePushMeasurements_CallInstance = CMock_Guts_MemChain(Mock.currentSensePushMeasurements_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_currentSensePushMeasurements(cmock_call_instance, push);
  UNITY_CLR_DETAILS();
}

void findCurrentSensors(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_findCurrentSensors_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_findCurrentSensors);
  cmock_call_instance = (CMOCK_findCurrentSensors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.findCurrentSensors_CallInstance);
  Mock.findCurrentSensors_CallInstance = CMock_Guts_MemNext(Mock.findCurrentSensors_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void findCurrentSensors_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_findCurrentSensors_CALL_INSTANCE));
  CMOCK_findCurrentSensors_CALL_INSTANCE* cmock_call_instance = (CMOCK_findCurrentSensors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.findCurrentSensors_CallInstance = CMock_Guts_MemChain(Mock.findCurrentSensors_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

uint8_t currentSenseCount(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_currentSenseCount_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_currentSenseCount);
  cmock_call_instance = (CMOCK_currentSenseCount_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.currentSenseCount_CallInstance);
  Mock.currentSenseCount_CallInstance = CMock_Guts_MemNext(Mock.currentSenseCount_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void currentSenseCount_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_currentSenseCount_CALL_INSTANCE));
  CMOCK_currentSenseCount_CALL_INSTANCE* cmock_call_instance = (CMOCK_currentSenseCount_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.currentSenseCount_CallInstance = CMock_Guts_MemChain(Mock.currentSenseCount_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void currentSenseBegin(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_currentSenseBegin_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_currentSenseBegin);
  cmock_call_instance = (CMOCK_currentSenseBegin_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.currentSenseBegin_CallInstance);
  Mock.currentSenseBegin_CallInstance = CMock_Guts_MemNext(Mock.currentSenseBegin_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void currentSenseBegin_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_currentSenseBegin_CALL_INSTANCE));
  CMOCK_currentSenseBegin_CALL_INSTANCE* cmock_call_instance = (CMOCK_currentSenseBegin_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.currentSenseBegin_CallInstance = CMock_Guts_MemChain(Mock.currentSenseBegin_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void currentSenseEnd(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_currentSenseEnd_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_currentSenseEnd);
  cmock_call_instance = (CMOCK_currentSenseEnd_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.currentSenseEnd_CallInstance);
  Mock.currentSenseEnd_CallInstance = CMock_Guts_MemNext(Mock.currentSenseEnd_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void currentSenseEnd_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_currentSenseEnd_CALL_INSTANCE));
  CMOCK_currentSenseEnd_CALL_INSTANCE* cmock_call_instance = (CMOCK_currentSenseEnd_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.currentSenseEnd_CallInstance = CMock_Guts_MemChain(Mock.currentSenseEnd_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

uint8_t currentSenseTask(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_currentSenseTask_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_currentSenseTask);
  cmock_call_instance = (CMOCK_currentSenseTask_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.currentSenseTask_CallInstance);
  Mock.currentSenseTask_CallInstance = CMock_Guts_MemNext(Mock.currentSenseTask_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void currentSenseTask_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_currentSenseTask_CALL_INSTANCE));
  CMOCK_currentSenseTask_CALL_INSTANCE* cmock_call_instance = (CMOCK_currentSenseTask_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.currentSenseTask_CallInstance = CMock_Guts_MemChain(Mock.currentSenseTask_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

uint8_t getAddress(uint8_t device)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_getAddress_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_getAddress);
  cmock_call_instance = (CMOCK_getAddress_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.getAddress_CallInstance);
  Mock.getAddress_CallInstance = CMock_Guts_MemNext(Mock.getAddress_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_getAddress,CMockString_device);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_device, device, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_getAddress(CMOCK_getAddress_CALL_INSTANCE* cmock_call_instance, uint8_t device)
{
  cmock_call_instance->Expected_device = device;
}

void getAddress_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t device, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_getAddress_CALL_INSTANCE));
  CMOCK_getAddress_CALL_INSTANCE* cmock_call_instance = (CMOCK_getAddress_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.getAddress_CallInstance = CMock_Guts_MemChain(Mock.getAddress_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_getAddress(cmock_call_instance, device);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void writeRegister(uint8_t address, uint8_t register_address, uint8_t value)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_writeRegister_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_writeRegister);
  cmock_call_instance = (CMOCK_writeRegister_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.writeRegister_CallInstance);
  Mock.writeRegister_CallInstance = CMock_Guts_MemNext(Mock.writeRegister_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_writeRegister,CMockString_address);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_address, address, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_writeRegister,CMockString_register_address);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_register_address, register_address, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_writeRegister,CMockString_value);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_value, value, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_writeRegister(CMOCK_writeRegister_CALL_INSTANCE* cmock_call_instance, uint8_t address, uint8_t register_address, uint8_t value)
{
  cmock_call_instance->Expected_address = address;
  cmock_call_instance->Expected_register_address = register_address;
  cmock_call_instance->Expected_value = value;
}

void writeRegister_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t address, uint8_t register_address, uint8_t value)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_writeRegister_CALL_INSTANCE));
  CMOCK_writeRegister_CALL_INSTANCE* cmock_call_instance = (CMOCK_writeRegister_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.writeRegister_CallInstance = CMock_Guts_MemChain(Mock.writeRegister_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_writeRegister(cmock_call_instance, address, register_address, value);
  UNITY_CLR_DETAILS();
}

void currentSenseClearMeasurements(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_currentSenseClearMeasurements_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_currentSenseClearMeasurements);
  cmock_call_instance = (CMOCK_currentSenseClearMeasurements_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.currentSenseClearMeasurements_CallInstance);
  Mock.currentSenseClearMeasurements_CallInstance = CMock_Guts_MemNext(Mock.currentSenseClearMeasurements_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void currentSenseClearMeasurements_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_currentSenseClearMeasurements_CALL_INSTANCE));
  CMOCK_currentSenseClearMeasurements_CALL_INSTANCE* cmock_call_instance = (CMOCK_currentSenseClearMeasurements_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.currentSenseClearMeasurements_CallInstance = CMock_Guts_MemChain(Mock.currentSenseClearMeasurements_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void printAccID(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_printAccID_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_printAccID);
  cmock_call_instance = (CMOCK_printAccID_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.printAccID_CallInstance);
  Mock.printAccID_CallInstance = CMock_Guts_MemNext(Mock.printAccID_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void printAccID_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_printAccID_CALL_INSTANCE));
  CMOCK_printAccID_CALL_INSTANCE* cmock_call_instance = (CMOCK_printAccID_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.printAccID_CallInstance = CMock_Guts_MemChain(Mock.printAccID_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void printCurrentProductId(uint8_t address)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_printCurrentProductId_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_printCurrentProductId);
  cmock_call_instance = (CMOCK_printCurrentProductId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.printCurrentProductId_CallInstance);
  Mock.printCurrentProductId_CallInstance = CMock_Guts_MemNext(Mock.printCurrentProductId_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_printCurrentProductId,CMockString_address);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_address, address, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_printCurrentProductId(CMOCK_printCurrentProductId_CALL_INSTANCE* cmock_call_instance, uint8_t address)
{
  cmock_call_instance->Expected_address = address;
}

void printCurrentProductId_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t address)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_printCurrentProductId_CALL_INSTANCE));
  CMOCK_printCurrentProductId_CALL_INSTANCE* cmock_call_instance = (CMOCK_printCurrentProductId_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.printCurrentProductId_CallInstance = CMock_Guts_MemChain(Mock.printCurrentProductId_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_printCurrentProductId(cmock_call_instance, address);
  UNITY_CLR_DETAILS();
}

float currentSenseConvert(uint8_t device, uint16_t sense)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_currentSenseConvert_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_currentSenseConvert);
  cmock_call_instance = (CMOCK_currentSenseConvert_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.currentSenseConvert_CallInstance);
  Mock.currentSenseConvert_CallInstance = CMock_Guts_MemNext(Mock.currentSenseConvert_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_currentSenseConvert,CMockString_device);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_device, device, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_currentSenseConvert,CMockString_sense);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_sense, sense, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_currentSenseConvert(CMOCK_currentSenseConvert_CALL_INSTANCE* cmock_call_instance, uint8_t device, uint16_t sense)
{
  cmock_call_instance->Expected_device = device;
  cmock_call_instance->Expected_sense = sense;
}

void currentSenseConvert_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t device, uint16_t sense, float cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_currentSenseConvert_CALL_INSTANCE));
  CMOCK_currentSenseConvert_CALL_INSTANCE* cmock_call_instance = (CMOCK_currentSenseConvert_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.currentSenseConvert_CallInstance = CMock_Guts_MemChain(Mock.currentSenseConvert_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_currentSenseConvert(cmock_call_instance, device, sense);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void printCurrent(uint8_t device)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_printCurrent_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_printCurrent);
  cmock_call_instance = (CMOCK_printCurrent_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.printCurrent_CallInstance);
  Mock.printCurrent_CallInstance = CMock_Guts_MemNext(Mock.printCurrent_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_printCurrent,CMockString_device);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_device, device, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_printCurrent(CMOCK_printCurrent_CALL_INSTANCE* cmock_call_instance, uint8_t device)
{
  cmock_call_instance->Expected_device = device;
}

void printCurrent_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t device)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_printCurrent_CALL_INSTANCE));
  CMOCK_printCurrent_CALL_INSTANCE* cmock_call_instance = (CMOCK_printCurrent_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.printCurrent_CallInstance = CMock_Guts_MemChain(Mock.printCurrent_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_printCurrent(cmock_call_instance, device);
  UNITY_CLR_DETAILS();
}

void printAccelerometerValues(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_printAccelerometerValues_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_printAccelerometerValues);
  cmock_call_instance = (CMOCK_printAccelerometerValues_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.printAccelerometerValues_CallInstance);
  Mock.printAccelerometerValues_CallInstance = CMock_Guts_MemNext(Mock.printAccelerometerValues_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void printAccelerometerValues_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_printAccelerometerValues_CALL_INSTANCE));
  CMOCK_printAccelerometerValues_CALL_INSTANCE* cmock_call_instance = (CMOCK_printAccelerometerValues_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.printAccelerometerValues_CallInstance = CMock_Guts_MemChain(Mock.printAccelerometerValues_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

uint16_t readCurrentSense(uint8_t address, uint8_t channel)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_readCurrentSense_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_readCurrentSense);
  cmock_call_instance = (CMOCK_readCurrentSense_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.readCurrentSense_CallInstance);
  Mock.readCurrentSense_CallInstance = CMock_Guts_MemNext(Mock.readCurrentSense_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_readCurrentSense,CMockString_address);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_address, address, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_readCurrentSense,CMockString_channel);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_channel, channel, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_readCurrentSense(CMOCK_readCurrentSense_CALL_INSTANCE* cmock_call_instance, uint8_t address, uint8_t channel)
{
  cmock_call_instance->Expected_address = address;
  cmock_call_instance->Expected_channel = channel;
}

void readCurrentSense_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t address, uint8_t channel, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_readCurrentSense_CALL_INSTANCE));
  CMOCK_readCurrentSense_CALL_INSTANCE* cmock_call_instance = (CMOCK_readCurrentSense_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.readCurrentSense_CallInstance = CMock_Guts_MemChain(Mock.readCurrentSense_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_readCurrentSense(cmock_call_instance, address, channel);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

uint16_t readCurrentSenseBlocking(uint8_t address, uint8_t channel)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_readCurrentSenseBlocking_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_readCurrentSenseBlocking);
  cmock_call_instance = (CMOCK_readCurrentSenseBlocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.readCurrentSenseBlocking_CallInstance);
  Mock.readCurrentSenseBlocking_CallInstance = CMock_Guts_MemNext(Mock.readCurrentSenseBlocking_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_readCurrentSenseBlocking,CMockString_address);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_address, address, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_readCurrentSenseBlocking,CMockString_channel);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_channel, channel, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_readCurrentSenseBlocking(CMOCK_readCurrentSenseBlocking_CALL_INSTANCE* cmock_call_instance, uint8_t address, uint8_t channel)
{
  cmock_call_instance->Expected_address = address;
  cmock_call_instance->Expected_channel = channel;
}

void readCurrentSenseBlocking_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t address, uint8_t channel, uint16_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_readCurrentSenseBlocking_CALL_INSTANCE));
  CMOCK_readCurrentSenseBlocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_readCurrentSenseBlocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.readCurrentSenseBlocking_CallInstance = CMock_Guts_MemChain(Mock.readCurrentSenseBlocking_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_readCurrentSenseBlocking(cmock_call_instance, address, channel);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void printCurrentSense(uint8_t address, uint8_t channel)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_printCurrentSense_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_printCurrentSense);
  cmock_call_instance = (CMOCK_printCurrentSense_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.printCurrentSense_CallInstance);
  Mock.printCurrentSense_CallInstance = CMock_Guts_MemNext(Mock.printCurrentSense_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_printCurrentSense,CMockString_address);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_address, address, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_printCurrentSense,CMockString_channel);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_channel, channel, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_printCurrentSense(CMOCK_printCurrentSense_CALL_INSTANCE* cmock_call_instance, uint8_t address, uint8_t channel)
{
  cmock_call_instance->Expected_address = address;
  cmock_call_instance->Expected_channel = channel;
}

void printCurrentSense_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t address, uint8_t channel)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_printCurrentSense_CALL_INSTANCE));
  CMOCK_printCurrentSense_CALL_INSTANCE* cmock_call_instance = (CMOCK_printCurrentSense_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.printCurrentSense_CallInstance = CMock_Guts_MemChain(Mock.printCurrentSense_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_printCurrentSense(cmock_call_instance, address, channel);
  UNITY_CLR_DETAILS();
}

void printCurrentMeasurement(currentMeasurement c)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_printCurrentMeasurement_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_printCurrentMeasurement);
  cmock_call_instance = (CMOCK_printCurrentMeasurement_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.printCurrentMeasurement_CallInstance);
  Mock.printCurrentMeasurement_CallInstance = CMock_Guts_MemNext(Mock.printCurrentMeasurement_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_printCurrentMeasurement,CMockString_c);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_c), (void*)(&c), sizeof(currentMeasurement), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_printCurrentMeasurement(CMOCK_printCurrentMeasurement_CALL_INSTANCE* cmock_call_instance, currentMeasurement c)
{
  memcpy(&cmock_call_instance->Expected_c, &c, sizeof(currentMeasurement));
}

void printCurrentMeasurement_CMockExpect(UNITY_LINE_TYPE cmock_line, currentMeasurement c)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_printCurrentMeasurement_CALL_INSTANCE));
  CMOCK_printCurrentMeasurement_CALL_INSTANCE* cmock_call_instance = (CMOCK_printCurrentMeasurement_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.printCurrentMeasurement_CallInstance = CMock_Guts_MemChain(Mock.printCurrentMeasurement_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_printCurrentMeasurement(cmock_call_instance, c);
  UNITY_CLR_DETAILS();
}

void printCurrentMeasurementFloat(currentMeasurementFloat c)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_printCurrentMeasurementFloat_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_printCurrentMeasurementFloat);
  cmock_call_instance = (CMOCK_printCurrentMeasurementFloat_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.printCurrentMeasurementFloat_CallInstance);
  Mock.printCurrentMeasurementFloat_CallInstance = CMock_Guts_MemNext(Mock.printCurrentMeasurementFloat_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_printCurrentMeasurementFloat,CMockString_c);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_c), (void*)(&c), sizeof(currentMeasurementFloat), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_printCurrentMeasurementFloat(CMOCK_printCurrentMeasurementFloat_CALL_INSTANCE* cmock_call_instance, currentMeasurementFloat c)
{
  memcpy(&cmock_call_instance->Expected_c, &c, sizeof(currentMeasurementFloat));
}

void printCurrentMeasurementFloat_CMockExpect(UNITY_LINE_TYPE cmock_line, currentMeasurementFloat c)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_printCurrentMeasurementFloat_CALL_INSTANCE));
  CMOCK_printCurrentMeasurementFloat_CALL_INSTANCE* cmock_call_instance = (CMOCK_printCurrentMeasurementFloat_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.printCurrentMeasurementFloat_CallInstance = CMock_Guts_MemChain(Mock.printCurrentMeasurementFloat_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_printCurrentMeasurementFloat(cmock_call_instance, c);
  UNITY_CLR_DETAILS();
}

void printAllCurrentMeasurementsFloat(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_printAllCurrentMeasurementsFloat_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_printAllCurrentMeasurementsFloat);
  cmock_call_instance = (CMOCK_printAllCurrentMeasurementsFloat_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.printAllCurrentMeasurementsFloat_CallInstance);
  Mock.printAllCurrentMeasurementsFloat_CallInstance = CMock_Guts_MemNext(Mock.printAllCurrentMeasurementsFloat_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void printAllCurrentMeasurementsFloat_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_printAllCurrentMeasurementsFloat_CALL_INSTANCE));
  CMOCK_printAllCurrentMeasurementsFloat_CALL_INSTANCE* cmock_call_instance = (CMOCK_printAllCurrentMeasurementsFloat_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.printAllCurrentMeasurementsFloat_CallInstance = CMock_Guts_MemChain(Mock.printAllCurrentMeasurementsFloat_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

float fetchCurrent(uint8_t device)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fetchCurrent_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fetchCurrent);
  cmock_call_instance = (CMOCK_fetchCurrent_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fetchCurrent_CallInstance);
  Mock.fetchCurrent_CallInstance = CMock_Guts_MemNext(Mock.fetchCurrent_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_fetchCurrent,CMockString_device);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_device, device, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fetchCurrent(CMOCK_fetchCurrent_CALL_INSTANCE* cmock_call_instance, uint8_t device)
{
  cmock_call_instance->Expected_device = device;
}

void fetchCurrent_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t device, float cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fetchCurrent_CALL_INSTANCE));
  CMOCK_fetchCurrent_CALL_INSTANCE* cmock_call_instance = (CMOCK_fetchCurrent_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fetchCurrent_CallInstance = CMock_Guts_MemChain(Mock.fetchCurrent_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_fetchCurrent(cmock_call_instance, device);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

currentMeasurementFloat fetchCurrentMeasurementFloat(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fetchCurrentMeasurementFloat_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fetchCurrentMeasurementFloat);
  cmock_call_instance = (CMOCK_fetchCurrentMeasurementFloat_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fetchCurrentMeasurementFloat_CallInstance);
  Mock.fetchCurrentMeasurementFloat_CallInstance = CMock_Guts_MemNext(Mock.fetchCurrentMeasurementFloat_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void fetchCurrentMeasurementFloat_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, currentMeasurementFloat cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fetchCurrentMeasurementFloat_CALL_INSTANCE));
  CMOCK_fetchCurrentMeasurementFloat_CALL_INSTANCE* cmock_call_instance = (CMOCK_fetchCurrentMeasurementFloat_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fetchCurrentMeasurementFloat_CallInstance = CMock_Guts_MemChain(Mock.fetchCurrentMeasurementFloat_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(currentMeasurementFloat));
  UNITY_CLR_DETAILS();
}

void currentSenseStartAll(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_currentSenseStartAll_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_currentSenseStartAll);
  cmock_call_instance = (CMOCK_currentSenseStartAll_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.currentSenseStartAll_CallInstance);
  Mock.currentSenseStartAll_CallInstance = CMock_Guts_MemNext(Mock.currentSenseStartAll_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void currentSenseStartAll_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_currentSenseStartAll_CALL_INSTANCE));
  CMOCK_currentSenseStartAll_CALL_INSTANCE* cmock_call_instance = (CMOCK_currentSenseStartAll_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.currentSenseStartAll_CallInstance = CMock_Guts_MemChain(Mock.currentSenseStartAll_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

