/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockcurrent_measurement.h"

static const char* CMockString_buf = "buf";
static const char* CMockString_converted = "converted";
static const char* CMockString_currentMeasurementConvert = "currentMeasurementConvert";
static const char* CMockString_measurement = "measurement";
static const char* CMockString_popCurrentMeasurement = "popCurrentMeasurement";
static const char* CMockString_pushCurrentMeasurement = "pushCurrentMeasurement";

typedef struct _CMOCK_pushCurrentMeasurement_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;
  circularBuffer* Expected_buf;
  currentMeasurement* Expected_measurement;

} CMOCK_pushCurrentMeasurement_CALL_INSTANCE;

typedef struct _CMOCK_popCurrentMeasurement_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t ReturnVal;
  circularBuffer* Expected_buf;
  currentMeasurementFloat* Expected_measurement;

} CMOCK_popCurrentMeasurement_CALL_INSTANCE;

typedef struct _CMOCK_currentMeasurementConvert_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  currentMeasurement* Expected_measurement;
  currentMeasurementFloat* Expected_converted;

} CMOCK_currentMeasurementConvert_CALL_INSTANCE;

static struct Mockcurrent_measurementInstance
{
  CMOCK_MEM_INDEX_TYPE pushCurrentMeasurement_CallInstance;
  CMOCK_MEM_INDEX_TYPE popCurrentMeasurement_CallInstance;
  CMOCK_MEM_INDEX_TYPE currentMeasurementConvert_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockcurrent_measurement_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_pushCurrentMeasurement);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.pushCurrentMeasurement_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_popCurrentMeasurement);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.popCurrentMeasurement_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_currentMeasurementConvert);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.currentMeasurementConvert_CallInstance, cmock_line, CMockStringCalledLess);
}

void Mockcurrent_measurement_Init(void)
{
  Mockcurrent_measurement_Destroy();
}

void Mockcurrent_measurement_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

uint8_t pushCurrentMeasurement(circularBuffer* buf, currentMeasurement* measurement)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_pushCurrentMeasurement_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_pushCurrentMeasurement);
  cmock_call_instance = (CMOCK_pushCurrentMeasurement_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.pushCurrentMeasurement_CallInstance);
  Mock.pushCurrentMeasurement_CallInstance = CMock_Guts_MemNext(Mock.pushCurrentMeasurement_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_pushCurrentMeasurement,CMockString_buf);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_buf), (void*)(buf), sizeof(circularBuffer), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_pushCurrentMeasurement,CMockString_measurement);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_measurement), (void*)(measurement), sizeof(currentMeasurement), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_pushCurrentMeasurement(CMOCK_pushCurrentMeasurement_CALL_INSTANCE* cmock_call_instance, circularBuffer* buf, currentMeasurement* measurement)
{
  cmock_call_instance->Expected_buf = buf;
  cmock_call_instance->Expected_measurement = measurement;
}

void pushCurrentMeasurement_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, circularBuffer* buf, currentMeasurement* measurement, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_pushCurrentMeasurement_CALL_INSTANCE));
  CMOCK_pushCurrentMeasurement_CALL_INSTANCE* cmock_call_instance = (CMOCK_pushCurrentMeasurement_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.pushCurrentMeasurement_CallInstance = CMock_Guts_MemChain(Mock.pushCurrentMeasurement_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_pushCurrentMeasurement(cmock_call_instance, buf, measurement);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

uint8_t popCurrentMeasurement(circularBuffer* buf, currentMeasurementFloat* measurement)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_popCurrentMeasurement_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_popCurrentMeasurement);
  cmock_call_instance = (CMOCK_popCurrentMeasurement_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.popCurrentMeasurement_CallInstance);
  Mock.popCurrentMeasurement_CallInstance = CMock_Guts_MemNext(Mock.popCurrentMeasurement_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_popCurrentMeasurement,CMockString_buf);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_buf), (void*)(buf), sizeof(circularBuffer), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_popCurrentMeasurement,CMockString_measurement);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_measurement), (void*)(measurement), sizeof(currentMeasurementFloat), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_popCurrentMeasurement(CMOCK_popCurrentMeasurement_CALL_INSTANCE* cmock_call_instance, circularBuffer* buf, currentMeasurementFloat* measurement)
{
  cmock_call_instance->Expected_buf = buf;
  cmock_call_instance->Expected_measurement = measurement;
}

void popCurrentMeasurement_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, circularBuffer* buf, currentMeasurementFloat* measurement, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_popCurrentMeasurement_CALL_INSTANCE));
  CMOCK_popCurrentMeasurement_CALL_INSTANCE* cmock_call_instance = (CMOCK_popCurrentMeasurement_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.popCurrentMeasurement_CallInstance = CMock_Guts_MemChain(Mock.popCurrentMeasurement_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_popCurrentMeasurement(cmock_call_instance, buf, measurement);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void currentMeasurementConvert(currentMeasurement* measurement, currentMeasurementFloat* converted)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_currentMeasurementConvert_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_currentMeasurementConvert);
  cmock_call_instance = (CMOCK_currentMeasurementConvert_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.currentMeasurementConvert_CallInstance);
  Mock.currentMeasurementConvert_CallInstance = CMock_Guts_MemNext(Mock.currentMeasurementConvert_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_currentMeasurementConvert,CMockString_measurement);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_measurement), (void*)(measurement), sizeof(currentMeasurement), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_currentMeasurementConvert,CMockString_converted);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_converted), (void*)(converted), sizeof(currentMeasurementFloat), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_currentMeasurementConvert(CMOCK_currentMeasurementConvert_CALL_INSTANCE* cmock_call_instance, currentMeasurement* measurement, currentMeasurementFloat* converted)
{
  cmock_call_instance->Expected_measurement = measurement;
  cmock_call_instance->Expected_converted = converted;
}

void currentMeasurementConvert_CMockExpect(UNITY_LINE_TYPE cmock_line, currentMeasurement* measurement, currentMeasurementFloat* converted)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_currentMeasurementConvert_CALL_INSTANCE));
  CMOCK_currentMeasurementConvert_CALL_INSTANCE* cmock_call_instance = (CMOCK_currentMeasurementConvert_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.currentMeasurementConvert_CallInstance = CMock_Guts_MemChain(Mock.currentMeasurementConvert_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_currentMeasurementConvert(cmock_call_instance, measurement, converted);
  UNITY_CLR_DETAILS();
}

