/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "lib/i2cmaster/Mocki2cmaster.h"

static const char* CMockString_data = "data";
static const char* CMockString_i2c_disable = "i2c_disable";
static const char* CMockString_i2c_enable = "i2c_enable";
static const char* CMockString_i2c_getData = "i2c_getData";
static const char* CMockString_i2c_readAck_nonblocking = "i2c_readAck_nonblocking";
static const char* CMockString_i2c_readNak_nonblocking = "i2c_readNak_nonblocking";
static const char* CMockString_i2c_start_nonblocking = "i2c_start_nonblocking";
static const char* CMockString_i2c_status = "i2c_status";
static const char* CMockString_i2c_stop_nonblocking = "i2c_stop_nonblocking";
static const char* CMockString_i2c_write_nonblocking = "i2c_write_nonblocking";

typedef struct _CMOCK_i2c_disable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  CEXCEPTION_T ExceptionToThrow;

} CMOCK_i2c_disable_CALL_INSTANCE;

typedef struct _CMOCK_i2c_enable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  CEXCEPTION_T ExceptionToThrow;

} CMOCK_i2c_enable_CALL_INSTANCE;

typedef struct _CMOCK_i2c_status_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint8_t ReturnVal;
  CEXCEPTION_T ExceptionToThrow;

} CMOCK_i2c_status_CALL_INSTANCE;

typedef struct _CMOCK_i2c_start_nonblocking_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  CEXCEPTION_T ExceptionToThrow;

} CMOCK_i2c_start_nonblocking_CALL_INSTANCE;

typedef struct _CMOCK_i2c_write_nonblocking_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  unsigned char Expected_data;
  CEXCEPTION_T ExceptionToThrow;
  int IgnoreArg_data;

} CMOCK_i2c_write_nonblocking_CALL_INSTANCE;

typedef struct _CMOCK_i2c_readAck_nonblocking_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  CEXCEPTION_T ExceptionToThrow;

} CMOCK_i2c_readAck_nonblocking_CALL_INSTANCE;

typedef struct _CMOCK_i2c_readNak_nonblocking_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  CEXCEPTION_T ExceptionToThrow;

} CMOCK_i2c_readNak_nonblocking_CALL_INSTANCE;

typedef struct _CMOCK_i2c_stop_nonblocking_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  CEXCEPTION_T ExceptionToThrow;

} CMOCK_i2c_stop_nonblocking_CALL_INSTANCE;

typedef struct _CMOCK_i2c_getData_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint8_t ReturnVal;
  CEXCEPTION_T ExceptionToThrow;

} CMOCK_i2c_getData_CALL_INSTANCE;

static struct Mocki2cmasterInstance
{
  int i2c_disable_IgnoreBool;
  CMOCK_i2c_disable_CALLBACK i2c_disable_CallbackFunctionPointer;
  int i2c_disable_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE i2c_disable_CallInstance;
  int i2c_enable_IgnoreBool;
  CMOCK_i2c_enable_CALLBACK i2c_enable_CallbackFunctionPointer;
  int i2c_enable_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE i2c_enable_CallInstance;
  int i2c_status_IgnoreBool;
  uint8_t i2c_status_FinalReturn;
  CMOCK_i2c_status_CALLBACK i2c_status_CallbackFunctionPointer;
  int i2c_status_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE i2c_status_CallInstance;
  int i2c_start_nonblocking_IgnoreBool;
  CMOCK_i2c_start_nonblocking_CALLBACK i2c_start_nonblocking_CallbackFunctionPointer;
  int i2c_start_nonblocking_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE i2c_start_nonblocking_CallInstance;
  int i2c_write_nonblocking_IgnoreBool;
  CMOCK_i2c_write_nonblocking_CALLBACK i2c_write_nonblocking_CallbackFunctionPointer;
  int i2c_write_nonblocking_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE i2c_write_nonblocking_CallInstance;
  int i2c_readAck_nonblocking_IgnoreBool;
  CMOCK_i2c_readAck_nonblocking_CALLBACK i2c_readAck_nonblocking_CallbackFunctionPointer;
  int i2c_readAck_nonblocking_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE i2c_readAck_nonblocking_CallInstance;
  int i2c_readNak_nonblocking_IgnoreBool;
  CMOCK_i2c_readNak_nonblocking_CALLBACK i2c_readNak_nonblocking_CallbackFunctionPointer;
  int i2c_readNak_nonblocking_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE i2c_readNak_nonblocking_CallInstance;
  int i2c_stop_nonblocking_IgnoreBool;
  CMOCK_i2c_stop_nonblocking_CALLBACK i2c_stop_nonblocking_CallbackFunctionPointer;
  int i2c_stop_nonblocking_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE i2c_stop_nonblocking_CallInstance;
  int i2c_getData_IgnoreBool;
  uint8_t i2c_getData_FinalReturn;
  CMOCK_i2c_getData_CALLBACK i2c_getData_CallbackFunctionPointer;
  int i2c_getData_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE i2c_getData_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mocki2cmaster_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.i2c_disable_IgnoreBool)
    Mock.i2c_disable_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_i2c_disable);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.i2c_disable_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.i2c_disable_CallbackFunctionPointer != NULL)
    Mock.i2c_disable_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.i2c_enable_IgnoreBool)
    Mock.i2c_enable_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_i2c_enable);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.i2c_enable_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.i2c_enable_CallbackFunctionPointer != NULL)
    Mock.i2c_enable_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.i2c_status_IgnoreBool)
    Mock.i2c_status_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_i2c_status);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.i2c_status_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.i2c_status_CallbackFunctionPointer != NULL)
    Mock.i2c_status_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.i2c_start_nonblocking_IgnoreBool)
    Mock.i2c_start_nonblocking_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_i2c_start_nonblocking);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.i2c_start_nonblocking_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.i2c_start_nonblocking_CallbackFunctionPointer != NULL)
    Mock.i2c_start_nonblocking_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.i2c_write_nonblocking_IgnoreBool)
    Mock.i2c_write_nonblocking_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_i2c_write_nonblocking);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.i2c_write_nonblocking_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.i2c_write_nonblocking_CallbackFunctionPointer != NULL)
    Mock.i2c_write_nonblocking_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.i2c_readAck_nonblocking_IgnoreBool)
    Mock.i2c_readAck_nonblocking_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_i2c_readAck_nonblocking);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.i2c_readAck_nonblocking_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.i2c_readAck_nonblocking_CallbackFunctionPointer != NULL)
    Mock.i2c_readAck_nonblocking_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.i2c_readNak_nonblocking_IgnoreBool)
    Mock.i2c_readNak_nonblocking_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_i2c_readNak_nonblocking);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.i2c_readNak_nonblocking_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.i2c_readNak_nonblocking_CallbackFunctionPointer != NULL)
    Mock.i2c_readNak_nonblocking_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.i2c_stop_nonblocking_IgnoreBool)
    Mock.i2c_stop_nonblocking_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_i2c_stop_nonblocking);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.i2c_stop_nonblocking_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.i2c_stop_nonblocking_CallbackFunctionPointer != NULL)
    Mock.i2c_stop_nonblocking_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.i2c_getData_IgnoreBool)
    Mock.i2c_getData_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_i2c_getData);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.i2c_getData_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.i2c_getData_CallbackFunctionPointer != NULL)
    Mock.i2c_getData_CallInstance = CMOCK_GUTS_NONE;
}

void Mocki2cmaster_Init(void)
{
  Mocki2cmaster_Destroy();
}

void Mocki2cmaster_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.i2c_disable_CallbackFunctionPointer = NULL;
  Mock.i2c_disable_CallbackCalls = 0;
  Mock.i2c_enable_CallbackFunctionPointer = NULL;
  Mock.i2c_enable_CallbackCalls = 0;
  Mock.i2c_status_CallbackFunctionPointer = NULL;
  Mock.i2c_status_CallbackCalls = 0;
  Mock.i2c_start_nonblocking_CallbackFunctionPointer = NULL;
  Mock.i2c_start_nonblocking_CallbackCalls = 0;
  Mock.i2c_write_nonblocking_CallbackFunctionPointer = NULL;
  Mock.i2c_write_nonblocking_CallbackCalls = 0;
  Mock.i2c_readAck_nonblocking_CallbackFunctionPointer = NULL;
  Mock.i2c_readAck_nonblocking_CallbackCalls = 0;
  Mock.i2c_readNak_nonblocking_CallbackFunctionPointer = NULL;
  Mock.i2c_readNak_nonblocking_CallbackCalls = 0;
  Mock.i2c_stop_nonblocking_CallbackFunctionPointer = NULL;
  Mock.i2c_stop_nonblocking_CallbackCalls = 0;
  Mock.i2c_getData_CallbackFunctionPointer = NULL;
  Mock.i2c_getData_CallbackCalls = 0;
}

void i2c_disable(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_i2c_disable_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_i2c_disable);
  cmock_call_instance = (CMOCK_i2c_disable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.i2c_disable_CallInstance);
  Mock.i2c_disable_CallInstance = CMock_Guts_MemNext(Mock.i2c_disable_CallInstance);
  if (Mock.i2c_disable_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.i2c_disable_CallbackFunctionPointer != NULL)
  {
    Mock.i2c_disable_CallbackFunctionPointer(Mock.i2c_disable_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
}

void i2c_disable_CMockIgnore(void)
{
  Mock.i2c_disable_IgnoreBool = (int)1;
}

void i2c_disable_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_disable_CALL_INSTANCE));
  CMOCK_i2c_disable_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_disable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_disable_CallInstance = CMock_Guts_MemChain(Mock.i2c_disable_CallInstance, cmock_guts_index);
  Mock.i2c_disable_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void i2c_disable_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_disable_CALL_INSTANCE));
  CMOCK_i2c_disable_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_disable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_disable_CallInstance = CMock_Guts_MemChain(Mock.i2c_disable_CallInstance, cmock_guts_index);
  Mock.i2c_disable_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  UNITY_CLR_DETAILS();
}

void i2c_disable_StubWithCallback(CMOCK_i2c_disable_CALLBACK Callback)
{
  Mock.i2c_disable_IgnoreBool = (int)0;
  Mock.i2c_disable_CallbackFunctionPointer = Callback;
}

void i2c_disable_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_disable_CALL_INSTANCE));
  CMOCK_i2c_disable_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_disable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_disable_CallInstance = CMock_Guts_MemChain(Mock.i2c_disable_CallInstance, cmock_guts_index);
  Mock.i2c_disable_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

void i2c_enable(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_i2c_enable_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_i2c_enable);
  cmock_call_instance = (CMOCK_i2c_enable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.i2c_enable_CallInstance);
  Mock.i2c_enable_CallInstance = CMock_Guts_MemNext(Mock.i2c_enable_CallInstance);
  if (Mock.i2c_enable_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.i2c_enable_CallbackFunctionPointer != NULL)
  {
    Mock.i2c_enable_CallbackFunctionPointer(Mock.i2c_enable_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
}

void i2c_enable_CMockIgnore(void)
{
  Mock.i2c_enable_IgnoreBool = (int)1;
}

void i2c_enable_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_enable_CALL_INSTANCE));
  CMOCK_i2c_enable_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_enable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_enable_CallInstance = CMock_Guts_MemChain(Mock.i2c_enable_CallInstance, cmock_guts_index);
  Mock.i2c_enable_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void i2c_enable_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_enable_CALL_INSTANCE));
  CMOCK_i2c_enable_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_enable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_enable_CallInstance = CMock_Guts_MemChain(Mock.i2c_enable_CallInstance, cmock_guts_index);
  Mock.i2c_enable_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  UNITY_CLR_DETAILS();
}

void i2c_enable_StubWithCallback(CMOCK_i2c_enable_CALLBACK Callback)
{
  Mock.i2c_enable_IgnoreBool = (int)0;
  Mock.i2c_enable_CallbackFunctionPointer = Callback;
}

void i2c_enable_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_enable_CALL_INSTANCE));
  CMOCK_i2c_enable_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_enable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_enable_CallInstance = CMock_Guts_MemChain(Mock.i2c_enable_CallInstance, cmock_guts_index);
  Mock.i2c_enable_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

uint8_t i2c_status(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_i2c_status_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_i2c_status);
  cmock_call_instance = (CMOCK_i2c_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.i2c_status_CallInstance);
  Mock.i2c_status_CallInstance = CMock_Guts_MemNext(Mock.i2c_status_CallInstance);
  if (Mock.i2c_status_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.i2c_status_FinalReturn;
    Mock.i2c_status_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.i2c_status_CallbackFunctionPointer != NULL)
  {
    return Mock.i2c_status_CallbackFunctionPointer(Mock.i2c_status_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void i2c_status_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_status_CALL_INSTANCE));
  CMOCK_i2c_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_status_CallInstance = CMock_Guts_MemChain(Mock.i2c_status_CallInstance, cmock_guts_index);
  Mock.i2c_status_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.i2c_status_IgnoreBool = (int)1;
}

void i2c_status_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_status_CALL_INSTANCE));
  CMOCK_i2c_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_status_CallInstance = CMock_Guts_MemChain(Mock.i2c_status_CallInstance, cmock_guts_index);
  Mock.i2c_status_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void i2c_status_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_status_CALL_INSTANCE));
  CMOCK_i2c_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_status_CallInstance = CMock_Guts_MemChain(Mock.i2c_status_CallInstance, cmock_guts_index);
  Mock.i2c_status_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void i2c_status_StubWithCallback(CMOCK_i2c_status_CALLBACK Callback)
{
  Mock.i2c_status_IgnoreBool = (int)0;
  Mock.i2c_status_CallbackFunctionPointer = Callback;
}

void i2c_status_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_status_CALL_INSTANCE));
  CMOCK_i2c_status_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_status_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_status_CallInstance = CMock_Guts_MemChain(Mock.i2c_status_CallInstance, cmock_guts_index);
  Mock.i2c_status_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

void i2c_start_nonblocking(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_i2c_start_nonblocking_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_i2c_start_nonblocking);
  cmock_call_instance = (CMOCK_i2c_start_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.i2c_start_nonblocking_CallInstance);
  Mock.i2c_start_nonblocking_CallInstance = CMock_Guts_MemNext(Mock.i2c_start_nonblocking_CallInstance);
  if (Mock.i2c_start_nonblocking_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.i2c_start_nonblocking_CallbackFunctionPointer != NULL)
  {
    Mock.i2c_start_nonblocking_CallbackFunctionPointer(Mock.i2c_start_nonblocking_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
}

void i2c_start_nonblocking_CMockIgnore(void)
{
  Mock.i2c_start_nonblocking_IgnoreBool = (int)1;
}

void i2c_start_nonblocking_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_start_nonblocking_CALL_INSTANCE));
  CMOCK_i2c_start_nonblocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_start_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_start_nonblocking_CallInstance = CMock_Guts_MemChain(Mock.i2c_start_nonblocking_CallInstance, cmock_guts_index);
  Mock.i2c_start_nonblocking_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void i2c_start_nonblocking_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_start_nonblocking_CALL_INSTANCE));
  CMOCK_i2c_start_nonblocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_start_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_start_nonblocking_CallInstance = CMock_Guts_MemChain(Mock.i2c_start_nonblocking_CallInstance, cmock_guts_index);
  Mock.i2c_start_nonblocking_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  UNITY_CLR_DETAILS();
}

void i2c_start_nonblocking_StubWithCallback(CMOCK_i2c_start_nonblocking_CALLBACK Callback)
{
  Mock.i2c_start_nonblocking_IgnoreBool = (int)0;
  Mock.i2c_start_nonblocking_CallbackFunctionPointer = Callback;
}

void i2c_start_nonblocking_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_start_nonblocking_CALL_INSTANCE));
  CMOCK_i2c_start_nonblocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_start_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_start_nonblocking_CallInstance = CMock_Guts_MemChain(Mock.i2c_start_nonblocking_CallInstance, cmock_guts_index);
  Mock.i2c_start_nonblocking_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

void i2c_write_nonblocking(unsigned char data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_i2c_write_nonblocking_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_i2c_write_nonblocking);
  cmock_call_instance = (CMOCK_i2c_write_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.i2c_write_nonblocking_CallInstance);
  Mock.i2c_write_nonblocking_CallInstance = CMock_Guts_MemNext(Mock.i2c_write_nonblocking_CallInstance);
  if (Mock.i2c_write_nonblocking_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.i2c_write_nonblocking_CallbackFunctionPointer != NULL)
  {
    Mock.i2c_write_nonblocking_CallbackFunctionPointer(data, Mock.i2c_write_nonblocking_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_data)
  {
    UNITY_SET_DETAILS(CMockString_i2c_write_nonblocking,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_data, data, cmock_line, CMockStringMismatch);
  }
  }
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_i2c_write_nonblocking(CMOCK_i2c_write_nonblocking_CALL_INSTANCE* cmock_call_instance, unsigned char data)
{
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->IgnoreArg_data = 0;
}

void i2c_write_nonblocking_CMockIgnore(void)
{
  Mock.i2c_write_nonblocking_IgnoreBool = (int)1;
}

void i2c_write_nonblocking_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_write_nonblocking_CALL_INSTANCE));
  CMOCK_i2c_write_nonblocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_write_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_write_nonblocking_CallInstance = CMock_Guts_MemChain(Mock.i2c_write_nonblocking_CallInstance, cmock_guts_index);
  Mock.i2c_write_nonblocking_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void i2c_write_nonblocking_CMockExpect(UNITY_LINE_TYPE cmock_line, unsigned char data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_write_nonblocking_CALL_INSTANCE));
  CMOCK_i2c_write_nonblocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_write_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_write_nonblocking_CallInstance = CMock_Guts_MemChain(Mock.i2c_write_nonblocking_CallInstance, cmock_guts_index);
  Mock.i2c_write_nonblocking_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_i2c_write_nonblocking(cmock_call_instance, data);
  UNITY_CLR_DETAILS();
}

void i2c_write_nonblocking_StubWithCallback(CMOCK_i2c_write_nonblocking_CALLBACK Callback)
{
  Mock.i2c_write_nonblocking_IgnoreBool = (int)0;
  Mock.i2c_write_nonblocking_CallbackFunctionPointer = Callback;
}

void i2c_write_nonblocking_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, unsigned char data, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_write_nonblocking_CALL_INSTANCE));
  CMOCK_i2c_write_nonblocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_write_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_write_nonblocking_CallInstance = CMock_Guts_MemChain(Mock.i2c_write_nonblocking_CallInstance, cmock_guts_index);
  Mock.i2c_write_nonblocking_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_i2c_write_nonblocking(cmock_call_instance, data);
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

void i2c_write_nonblocking_CMockIgnoreArg_data(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_i2c_write_nonblocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_write_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.i2c_write_nonblocking_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_data = 1;
}

void i2c_readAck_nonblocking(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_i2c_readAck_nonblocking_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_i2c_readAck_nonblocking);
  cmock_call_instance = (CMOCK_i2c_readAck_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.i2c_readAck_nonblocking_CallInstance);
  Mock.i2c_readAck_nonblocking_CallInstance = CMock_Guts_MemNext(Mock.i2c_readAck_nonblocking_CallInstance);
  if (Mock.i2c_readAck_nonblocking_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.i2c_readAck_nonblocking_CallbackFunctionPointer != NULL)
  {
    Mock.i2c_readAck_nonblocking_CallbackFunctionPointer(Mock.i2c_readAck_nonblocking_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
}

void i2c_readAck_nonblocking_CMockIgnore(void)
{
  Mock.i2c_readAck_nonblocking_IgnoreBool = (int)1;
}

void i2c_readAck_nonblocking_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_readAck_nonblocking_CALL_INSTANCE));
  CMOCK_i2c_readAck_nonblocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_readAck_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_readAck_nonblocking_CallInstance = CMock_Guts_MemChain(Mock.i2c_readAck_nonblocking_CallInstance, cmock_guts_index);
  Mock.i2c_readAck_nonblocking_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void i2c_readAck_nonblocking_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_readAck_nonblocking_CALL_INSTANCE));
  CMOCK_i2c_readAck_nonblocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_readAck_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_readAck_nonblocking_CallInstance = CMock_Guts_MemChain(Mock.i2c_readAck_nonblocking_CallInstance, cmock_guts_index);
  Mock.i2c_readAck_nonblocking_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  UNITY_CLR_DETAILS();
}

void i2c_readAck_nonblocking_StubWithCallback(CMOCK_i2c_readAck_nonblocking_CALLBACK Callback)
{
  Mock.i2c_readAck_nonblocking_IgnoreBool = (int)0;
  Mock.i2c_readAck_nonblocking_CallbackFunctionPointer = Callback;
}

void i2c_readAck_nonblocking_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_readAck_nonblocking_CALL_INSTANCE));
  CMOCK_i2c_readAck_nonblocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_readAck_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_readAck_nonblocking_CallInstance = CMock_Guts_MemChain(Mock.i2c_readAck_nonblocking_CallInstance, cmock_guts_index);
  Mock.i2c_readAck_nonblocking_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

void i2c_readNak_nonblocking(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_i2c_readNak_nonblocking_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_i2c_readNak_nonblocking);
  cmock_call_instance = (CMOCK_i2c_readNak_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.i2c_readNak_nonblocking_CallInstance);
  Mock.i2c_readNak_nonblocking_CallInstance = CMock_Guts_MemNext(Mock.i2c_readNak_nonblocking_CallInstance);
  if (Mock.i2c_readNak_nonblocking_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.i2c_readNak_nonblocking_CallbackFunctionPointer != NULL)
  {
    Mock.i2c_readNak_nonblocking_CallbackFunctionPointer(Mock.i2c_readNak_nonblocking_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
}

void i2c_readNak_nonblocking_CMockIgnore(void)
{
  Mock.i2c_readNak_nonblocking_IgnoreBool = (int)1;
}

void i2c_readNak_nonblocking_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_readNak_nonblocking_CALL_INSTANCE));
  CMOCK_i2c_readNak_nonblocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_readNak_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_readNak_nonblocking_CallInstance = CMock_Guts_MemChain(Mock.i2c_readNak_nonblocking_CallInstance, cmock_guts_index);
  Mock.i2c_readNak_nonblocking_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void i2c_readNak_nonblocking_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_readNak_nonblocking_CALL_INSTANCE));
  CMOCK_i2c_readNak_nonblocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_readNak_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_readNak_nonblocking_CallInstance = CMock_Guts_MemChain(Mock.i2c_readNak_nonblocking_CallInstance, cmock_guts_index);
  Mock.i2c_readNak_nonblocking_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  UNITY_CLR_DETAILS();
}

void i2c_readNak_nonblocking_StubWithCallback(CMOCK_i2c_readNak_nonblocking_CALLBACK Callback)
{
  Mock.i2c_readNak_nonblocking_IgnoreBool = (int)0;
  Mock.i2c_readNak_nonblocking_CallbackFunctionPointer = Callback;
}

void i2c_readNak_nonblocking_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_readNak_nonblocking_CALL_INSTANCE));
  CMOCK_i2c_readNak_nonblocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_readNak_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_readNak_nonblocking_CallInstance = CMock_Guts_MemChain(Mock.i2c_readNak_nonblocking_CallInstance, cmock_guts_index);
  Mock.i2c_readNak_nonblocking_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

void i2c_stop_nonblocking(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_i2c_stop_nonblocking_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_i2c_stop_nonblocking);
  cmock_call_instance = (CMOCK_i2c_stop_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.i2c_stop_nonblocking_CallInstance);
  Mock.i2c_stop_nonblocking_CallInstance = CMock_Guts_MemNext(Mock.i2c_stop_nonblocking_CallInstance);
  if (Mock.i2c_stop_nonblocking_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.i2c_stop_nonblocking_CallbackFunctionPointer != NULL)
  {
    Mock.i2c_stop_nonblocking_CallbackFunctionPointer(Mock.i2c_stop_nonblocking_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
}

void i2c_stop_nonblocking_CMockIgnore(void)
{
  Mock.i2c_stop_nonblocking_IgnoreBool = (int)1;
}

void i2c_stop_nonblocking_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_stop_nonblocking_CALL_INSTANCE));
  CMOCK_i2c_stop_nonblocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_stop_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_stop_nonblocking_CallInstance = CMock_Guts_MemChain(Mock.i2c_stop_nonblocking_CallInstance, cmock_guts_index);
  Mock.i2c_stop_nonblocking_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void i2c_stop_nonblocking_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_stop_nonblocking_CALL_INSTANCE));
  CMOCK_i2c_stop_nonblocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_stop_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_stop_nonblocking_CallInstance = CMock_Guts_MemChain(Mock.i2c_stop_nonblocking_CallInstance, cmock_guts_index);
  Mock.i2c_stop_nonblocking_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  UNITY_CLR_DETAILS();
}

void i2c_stop_nonblocking_StubWithCallback(CMOCK_i2c_stop_nonblocking_CALLBACK Callback)
{
  Mock.i2c_stop_nonblocking_IgnoreBool = (int)0;
  Mock.i2c_stop_nonblocking_CallbackFunctionPointer = Callback;
}

void i2c_stop_nonblocking_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_stop_nonblocking_CALL_INSTANCE));
  CMOCK_i2c_stop_nonblocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_stop_nonblocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_stop_nonblocking_CallInstance = CMock_Guts_MemChain(Mock.i2c_stop_nonblocking_CallInstance, cmock_guts_index);
  Mock.i2c_stop_nonblocking_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

uint8_t i2c_getData(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_i2c_getData_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_i2c_getData);
  cmock_call_instance = (CMOCK_i2c_getData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.i2c_getData_CallInstance);
  Mock.i2c_getData_CallInstance = CMock_Guts_MemNext(Mock.i2c_getData_CallInstance);
  if (Mock.i2c_getData_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.i2c_getData_FinalReturn;
    Mock.i2c_getData_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.i2c_getData_CallbackFunctionPointer != NULL)
  {
    return Mock.i2c_getData_CallbackFunctionPointer(Mock.i2c_getData_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->ExceptionToThrow != CEXCEPTION_NONE)
  {
    UNITY_CLR_DETAILS();
    Throw(cmock_call_instance->ExceptionToThrow);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void i2c_getData_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_getData_CALL_INSTANCE));
  CMOCK_i2c_getData_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_getData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_getData_CallInstance = CMock_Guts_MemChain(Mock.i2c_getData_CallInstance, cmock_guts_index);
  Mock.i2c_getData_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.i2c_getData_IgnoreBool = (int)1;
}

void i2c_getData_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_getData_CALL_INSTANCE));
  CMOCK_i2c_getData_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_getData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_getData_CallInstance = CMock_Guts_MemChain(Mock.i2c_getData_CallInstance, cmock_guts_index);
  Mock.i2c_getData_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void i2c_getData_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_getData_CALL_INSTANCE));
  CMOCK_i2c_getData_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_getData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_getData_CallInstance = CMock_Guts_MemChain(Mock.i2c_getData_CallInstance, cmock_guts_index);
  Mock.i2c_getData_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void i2c_getData_StubWithCallback(CMOCK_i2c_getData_CALLBACK Callback)
{
  Mock.i2c_getData_IgnoreBool = (int)0;
  Mock.i2c_getData_CallbackFunctionPointer = Callback;
}

void i2c_getData_CMockExpectAndThrow(UNITY_LINE_TYPE cmock_line, CEXCEPTION_T cmock_to_throw)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_i2c_getData_CALL_INSTANCE));
  CMOCK_i2c_getData_CALL_INSTANCE* cmock_call_instance = (CMOCK_i2c_getData_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.i2c_getData_CallInstance = CMock_Guts_MemChain(Mock.i2c_getData_CallInstance, cmock_guts_index);
  Mock.i2c_getData_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExceptionToThrow = CEXCEPTION_NONE;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ExceptionToThrow = cmock_to_throw;
}

